"""Suricata invocation and eve.json parsing (docs/spec.md §8, PLAN.md step 6).

Suricata is invoked for real here — the testing line is *tools real, network stubbed*
(spec §2), and a mock would encode our assumptions about the very tool behaviour that needs
verifying. Those tests carry ``@pytest.mark.requires_tools``. Nothing in this file makes a
network call or contacts a PANW device.

Two things are synthesized rather than sourced, both so the expected result is
*known-correct* rather than empirical:

* **the rules** — ``tests/fixtures/rules/synthetic.rules``, whose header explains why they
  avoid ``$HOME_NET``;
* **the snapshot** — a hand-built directory (``rules.rules`` + ``manifest.json`` +
  ``raw/<source>.rules``) rather than one written by ``rules/snapshot.py``, which lands in
  step 4 and is being built in parallel. That keeps this step independently testable, and
  the layout it builds is the one spec §7 documents.

The TLS capture for the JA4 test is generated into ``tmp_path`` rather than committed:
``tests/fixtures/`` has a deliberately narrow ``.gitignore`` exception, and a capture that
can be regenerated byte-for-byte does not need to live in git.
"""

from __future__ import annotations

import dataclasses
import hashlib
import importlib.util
import ipaddress
import json
import re
import struct
import time
from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest

from flabel import suricata
from flabel.errors import SnapshotError, ToolError
from flabel.models import SnapshotManifest, SourceAdmission

FIXTURES = Path(__file__).resolve().parent / "fixtures"
BENIGN = FIXTURES / "benign.pcap"
SYNTHETIC_RULES = FIXTURES / "rules" / "synthetic.rules"

#: SIDs in ``synthetic.rules``; see that file for what each one matches.
HTTP_SID = 9000001
JA4_SID = 9000002
IDENTIFY_SID = 9000003
UNLOADABLE_SID = 9000004
HOME_NET_SID = 9000005
DNS_SID = 9000006
ICMP_SID = 9000007
ICMP6_SID = 9000008

#: A well-formed id that is not the hash of anything, for injecting an inconsistent snapshot.
WRONG_SNAPSHOT_ID = "0123456789abcdef"

#: Step 4's SID→source attribution file, which step 6 reads instead of re-deriving from `raw/`.
SID_INDEX = "sid_index.json"

#: The alert timestamp the HTTP rule must carry: ``make_canary.BASE_TS`` + 0.05s. The canary's
#: first flow runs one packet every 0.01s and the request is its 4th; Suricata raises the alert
#: on the 6th (``pcap_cnt`` 6), when the stream has been reassembled — i.e. on the packet
#: Suricata was looking at, not the one carrying the bytes. Asserted as an absolute epoch value
#: because correlation joins it against Zeek's epoch ``ts`` (spec §9).
HTTP_ALERT_TS = 1700000000.05

SEMVER = re.compile(r"\d+\.\d+\.\d+")


# --- fixture generators -------------------------------------------------------------------


def _load_canary() -> object:
    """Load ``make_canary.py`` as a module for its packet-building helpers.

    Imported rather than re-implemented: its IP/TCP checksum code is already verified
    against Zeek and Suricata, and a capture with a wrong checksum is exactly the kind of
    fixture that fails in a way no assertion explains. It is a fixture generator, not
    library code, hence the explicit file load.
    """
    spec = importlib.util.spec_from_file_location("flabel_make_canary", FIXTURES / "make_canary.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


CANARY = _load_canary()

TLS_CLIENT = "10.0.0.7"
TLS_SERVER = "10.0.0.202"
TLS_SPORT = 49200
TLS_BASE_TS = 1700000100.0


def _extension(kind: int, body: bytes) -> bytes:
    return struct.pack("!HH", kind, len(body)) + body


def _client_hello() -> bytes:
    """A TLS 1.3 ClientHello whose JA4_a segment is ``t13d0405h2``.

    Fixed content — including the 32 "random" bytes — so the JA4 value is identical on every
    run: TCP, TLS 1.3 (from ``supported_versions``), SNI present, 4 ciphers, 5 extensions,
    first ALPN ``h2``. That is what ``synthetic.rules`` sid 9000002 matches on.
    """
    host = b"flabel.test"
    server_name = _extension(0x0000, struct.pack("!HBH", len(host) + 3, 0, len(host)) + host)
    supported_groups = _extension(0x000A, struct.pack("!HH", 2, 0x001D))
    signature_algorithms = _extension(0x000D, struct.pack("!HHHH", 6, 0x0403, 0x0804, 0x0401))
    alpn_body = b"\x02h2"
    alpn = _extension(0x0010, struct.pack("!H", len(alpn_body)) + alpn_body)
    supported_versions = _extension(0x002B, struct.pack("!BHH", 4, 0x0304, 0x0303))
    extensions = server_name + supported_groups + signature_algorithms + alpn + supported_versions

    ciphers = struct.pack("!HHHH", 0x1301, 0x1302, 0x1303, 0xC02F)
    body = (
        struct.pack("!H", 0x0303)
        + bytes(range(32))
        + b"\x00"  # no session id
        + struct.pack("!H", len(ciphers))
        + ciphers
        + b"\x01\x00"  # compression: null only
        + struct.pack("!H", len(extensions))
        + extensions
    )
    handshake = b"\x01" + len(body).to_bytes(3, "big") + body
    return b"\x16\x03\x01" + struct.pack("!H", len(handshake)) + handshake


def write_tls_capture(path: Path) -> None:
    """One TCP flow to port 443 carrying the ClientHello above, byte-deterministic."""
    hello = _client_hello()
    client_seq, server_seq = 2000, 7000
    steps = [
        (TLS_CLIENT, TLS_SERVER, TLS_SPORT, 443, client_seq, 0, CANARY.SYN, b""),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq,
            client_seq + 1,
            CANARY.SYN | CANARY.ACK,
            b"",
        ),
        (TLS_CLIENT, TLS_SERVER, TLS_SPORT, 443, client_seq + 1, server_seq + 1, CANARY.ACK, b""),
        (
            TLS_CLIENT,
            TLS_SERVER,
            TLS_SPORT,
            443,
            client_seq + 1,
            server_seq + 1,
            CANARY.PSH | CANARY.ACK,
            hello,
        ),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq + 1,
            client_seq + 1 + len(hello),
            CANARY.ACK,
            b"",
        ),
        (
            TLS_CLIENT,
            TLS_SERVER,
            TLS_SPORT,
            443,
            client_seq + 1 + len(hello),
            server_seq + 1,
            CANARY.FIN | CANARY.ACK,
            b"",
        ),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq + 1,
            client_seq + 2 + len(hello),
            CANARY.FIN | CANARY.ACK,
            b"",
        ),
    ]

    packets = []
    for index, (src, dst, sport, dport, seq, ack, flags, payload) in enumerate(steps):
        segment = CANARY.tcp(sport, dport, seq, ack, flags, src, dst, payload)
        frame = CANARY.ethernet(CANARY.ipv4(src, dst, segment, ident=500 + index))
        packets.append((TLS_BASE_TS + index * 0.01, frame))
    CANARY.write_pcap(str(path), packets)


UDP_CLIENT = "10.0.0.9"
UDP_SERVER = "10.0.0.204"
UDP_SPORT = 53124
ICMP_CLIENT = "10.0.0.8"
ICMP_SERVER = "10.0.0.203"
ICMP6_CLIENT = "fd00::a1"
ICMP6_SERVER = "fd00::a2"
MIXED_BASE_TS = 1700000200.0


def _udp(sport: int, dport: int, payload: bytes, src: str, dst: str) -> bytes:
    length = 8 + len(payload)
    blank = struct.pack("!HHHH", sport, dport, length, 0) + payload
    pseudo = CANARY._packed_ip(src) + CANARY._packed_ip(dst) + struct.pack("!BBH", 0, 17, length)
    return struct.pack("!HHHH", sport, dport, length, CANARY.checksum(pseudo + blank)) + payload


def _dns_query(name: bytes = b"flabel-test.invalid") -> bytes:
    labels = b"".join(bytes([len(part)]) + part for part in name.split(b".")) + b"\x00"
    return struct.pack("!HHHHHH", 0x1234, 0x0100, 1, 0, 0, 0) + labels + struct.pack("!HH", 1, 1)


def _icmp4(kind: int, code: int) -> bytes:
    blank = struct.pack("!BBHHH", kind, code, 0, 1, 1) + b"flabel"
    return struct.pack("!BBHHH", kind, code, CANARY.checksum(blank), 1, 1) + b"flabel"


def _icmp6(kind: int, code: int, src: bytes, dst: bytes) -> bytes:
    body = struct.pack("!BBHHH", kind, code, 0, 1, 1) + b"flabel"
    pseudo = src + dst + struct.pack("!IBBBB", len(body), 0, 0, 0, 58)
    checksum = CANARY.checksum(pseudo + body)
    return struct.pack("!BBHHH", kind, code, checksum, 1, 1) + b"flabel"


def _ipv6(src: bytes, dst: bytes, payload: bytes, next_header: int) -> bytes:
    return struct.pack("!IHBB", 0x60000000, len(payload), next_header, 64) + src + dst + payload


def write_mixed_capture(path: Path) -> None:
    """A UDP DNS query plus ICMPv4 and ICMPv6 echoes: the protocols the canary lacks.

    Generated rather than committed, and generated *here* rather than added to
    `make_canary.py`, which the benign canary's "zero labels" guarantee depends on staying
    exactly as it is.
    """
    v6_src = ipaddress.ip_address(ICMP6_CLIENT).packed
    v6_dst = ipaddress.ip_address(ICMP6_SERVER).packed
    query = _dns_query()

    frames = [
        CANARY.ethernet(
            CANARY.ipv4(
                UDP_CLIENT,
                UDP_SERVER,
                _udp(UDP_SPORT, 53, query, UDP_CLIENT, UDP_SERVER),
                proto=17,
                ident=800,
            )
        ),
        CANARY.ethernet(CANARY.ipv4(ICMP_CLIENT, ICMP_SERVER, _icmp4(8, 0), proto=1, ident=801)),
        CANARY.ethernet(CANARY.ipv4(ICMP_SERVER, ICMP_CLIENT, _icmp4(0, 0), proto=1, ident=802)),
        _ETHER6 + _ipv6(v6_src, v6_dst, _icmp6(128, 0, v6_src, v6_dst), 58),
        _ETHER6 + _ipv6(v6_dst, v6_src, _icmp6(129, 0, v6_dst, v6_src), 58),
    ]
    CANARY.write_pcap(
        str(path), [(MIXED_BASE_TS + index * 0.01, frame) for index, frame in enumerate(frames)]
    )


#: An Ethernet header with the IPv6 ethertype; `make_canary.ethernet` hardcodes IPv4's.
_ETHER6 = CANARY.SRC_MAC + CANARY.DST_MAC + b"\x86\xdd"


def rule_lines() -> dict[int, str]:
    """The synthetic rules, keyed by SID."""
    lines = {}
    for line in SYNTHETIC_RULES.read_text(encoding="utf-8").splitlines():
        if not line.startswith("alert"):
            continue
        match = re.search(r"\bsid:(\d+);", line)
        assert match is not None, f"synthetic rule has no sid: {line}"
        lines[int(match.group(1))] = line
    return lines


RULES = rule_lines()


def make_snapshot(
    root: Path,
    contents: Mapping[str, Sequence[int]],
    classes: Mapping[str, str] | None = None,
    *,
    sid_index: bool = True,
    snapshot_id: str | None = None,
) -> Path:
    """Hand-build the snapshot layout of spec §7 from `contents` (source name → SIDs).

    Stands in for step 4's ``write_snapshot`` so this step stays independently testable. Writes
    the three files step 6 reads — ``rules.rules``, ``manifest.json`` and ``sid_index.json`` —
    and nothing else; ``raw/`` exists in a real snapshot for audit, and step 6 deliberately no
    longer looks at it. ``sid_index=False`` omits the attribution file, which is how "this
    snapshot cannot attribute its SIDs" is injected.

    `snapshot_id` defaults to the real ``sha256(rules.rules + sid_index.json)[:16]`` step 4
    writes, so fixtures are internally consistent the way a written snapshot is; pass a string
    to inject an id that does not match its own content.
    """
    classes = classes or {}
    snapshot = root / "snapshot"
    snapshot.mkdir(parents=True, exist_ok=True)

    admissions = []
    admitted: list[str] = []
    for name in sorted(contents):
        lines = [RULES[sid] for sid in sorted(contents[name])]
        admitted.extend(lines)
        admissions.append(
            SourceAdmission(
                name=name,
                url=f"https://example.invalid/{name}.rules",
                licence="MIT",
                source_class=classes.get(name, "signature"),
                admission_basis="wholesale",
                rules_fetched=len(lines),
                rules_admitted=len(lines),
                rules_excluded_no_confidence=0,
                rules_excluded_low_confidence=0,
                rules_excluded_low_severity=0,
                rules_excluded_commented=0,
                ja4_rules_admitted=sum("ja4.hash" in line for line in lines),
                ja3_rules_admitted=0,
                fetched_at="2026-08-12T00:00:00.000000Z",
            )
        )

    rules = snapshot / "rules.rules"
    rules.write_text("\n".join(admitted) + "\n" if admitted else "")

    if sid_index:
        (snapshot / SID_INDEX).write_text(
            json.dumps(
                {
                    "schema": 1,
                    "sources": {name: sorted(contents[name]) for name in sorted(contents)},
                },
                indent=2,
            )
        )

    manifest = SnapshotManifest(
        snapshot_id=snapshot_id or computed_snapshot_id(snapshot),
        created_at="2026-08-12T00:00:00.000000Z",
        flabel_version="0.0.0",
        sources=tuple(admissions),
        total_admitted=len(admitted),
        total_ja4_admitted=sum(admission.ja4_rules_admitted for admission in admissions),
    )
    (snapshot / "manifest.json").write_text(json.dumps(dataclasses.asdict(manifest), indent=2))
    return snapshot


def computed_snapshot_id(snapshot: Path) -> str:
    """The id step 4 writes: sha256 over the rules and their attribution, truncated to 16."""
    digest = hashlib.sha256()
    for name in ("rules.rules", SID_INDEX):
        path = snapshot / name
        digest.update(path.read_bytes() if path.exists() else b"")
    return digest.hexdigest()[:16]


def snapshot_id_of(snapshot: Path) -> str:
    """The id the manifest claims, read the way `provenance` will read it."""
    return json.loads((snapshot / "manifest.json").read_text())["snapshot_id"]


def reseal(snapshot: Path) -> None:
    """Recompute `snapshot_id` after a test has rewritten a hashed file.

    Needed because the id is verified against those files' contents: without this, every test
    that injects a *rules* or *attribution* fault would trip the consistency check first and
    prove nothing about the fault it meant to inject.
    """
    document = json.loads((snapshot / "manifest.json").read_text())
    document["snapshot_id"] = computed_snapshot_id(snapshot)
    (snapshot / "manifest.json").write_text(json.dumps(document, indent=2))


def set_sid_index(snapshot: Path, sources: Mapping[str, Sequence[int]], schema: int = 1) -> None:
    """Overwrite the attribution file and reseal, so only the attribution is under test."""
    (snapshot / SID_INDEX).write_text(
        json.dumps({"schema": schema, "sources": {name: list(sources[name]) for name in sources}})
    )
    reseal(snapshot)


# --- the invocation itself -----------------------------------------------------------------


def test_argv_loads_only_the_snapshot_ruleset():
    """The flags of spec §8, asserted as a contract rather than trusted to a comment.

    ``-S`` *replaces* the ruleset; ``-s`` would *add* to whatever the system config already
    loads. Getting that wrong is invisible in the output — labels would silently carry SIDs
    from rules that are in no snapshot, i.e. a verdict whose origin cannot be traced
    (spec §13). Same reasoning as step 5's regression test on Zeek's ``-D``.
    """
    # Resolved, not literal: `build_argv` absolutises every path, and on macOS `/tmp` is a
    # symlink to `/private/tmp`, so the expectation has to be resolved the same way.
    capture, snapshot, outdir = (
        Path("/tmp/cap.pcap").resolve(),
        Path("/snap").resolve(),
        Path("/out").resolve(),
    )
    argv = suricata.build_argv(capture, snapshot, outdir)

    assert argv[0] == "suricata"
    assert argv[argv.index("-r") + 1] == str(capture)
    assert argv[argv.index("-l") + 1] == str(outdir)
    assert argv[argv.index("-S") + 1] == str(snapshot / "rules.rules")
    assert "-s" not in argv, "-s adds to the system ruleset; only -S replaces it"
    assert "--rule-reload" not in argv
    assert argv[argv.index("--runmode") + 1] == "single"
    assert "--set" in argv
    assert "app-layer.protocols.tls.ja3-fingerprints=yes" in argv
    assert "app-layer.protocols.tls.ja4-fingerprints=yes" in argv


def test_argv_uses_flabels_own_config_not_the_machines():
    """``-c``, and the two config files it names, are part of the contract.

    Without ``-c`` the operator's `/etc/suricata/suricata.yaml` decides whether an abuse.ch
    ``$HOME_NET -> $EXTERNAL_NET`` rule can fire, what `classtype` text lands in provenance, and
    whether capture payloads are written to disk. `default-rule-path` is pinned to the snapshot
    so a rule's own relative paths (``dataset:``) cannot reach outside it.
    """
    argv = suricata.build_argv(Path("/tmp/cap.pcap"), Path("/snap"), Path("/out"))
    settings = {argv[index + 1] for index, value in enumerate(argv) if value == "--set"}

    config = Path(argv[argv.index("-c") + 1])
    assert config.name == "suricata.yaml"
    assert config.is_absolute() and config.exists(), "the config must ship as package data"
    assert f"classification-file={config.parent / 'classification.config'}" in settings
    assert f"reference-config-file={config.parent / 'reference.config'}" in settings
    assert f"default-rule-path={Path('/snap').resolve()}" in settings


def test_argv_paths_are_absolute_whatever_the_working_directory(tmp_path, monkeypatch):
    """A relative snapshot path must not reach the tool.

    Measured on 8.0.6: a relative ``-S`` is resolved against the working directory
    (``default-rule-path`` is *not* prepended, though the docs read as though it might be). Spec
    §12's default ``--rules-dir ./.flabel/rules`` is relative, so this is the ordinary case, and
    an argv that only works from one directory is not a reproducible failure report either.
    """
    monkeypatch.chdir(tmp_path)
    (tmp_path / "snap").mkdir()

    argv = suricata.build_argv(Path("cap.pcap"), Path("snap"), Path("out"))

    for flag in ("-r", "-S", "-l"):
        value = Path(argv[argv.index(flag) + 1])
        assert value.is_absolute(), f"{flag} was given the relative path {value}"
        assert str(value).startswith(str(tmp_path.resolve()))


def test_the_vendored_config_is_hashed_for_the_run_block():
    """One digest over every config file, so a run can say which configuration produced it.

    `HOME_NET`, the classtype descriptions and the eve output selection all change what a label
    says, so "same input, same output" is only meaningful against a known config (Goal 2).
    """
    digest = suricata.config_sha256()

    assert re.fullmatch(r"[0-9a-f]{64}", digest)
    names = [path.name for path in suricata.config_files()]
    assert names == ["suricata.yaml", "classification.config", "reference.config"]
    assert all(path.exists() for path in suricata.config_files())
    assert suricata.config_sha256() == digest, "the digest must not depend on read order"


@pytest.mark.requires_tools
def test_the_vendored_config_makes_a_home_net_rule_fire(tmp_path):
    """The point of `-c`, proved rather than asserted.

    `synthetic.rules` sid 9000005 is written the way the abuse.ch feeds write their C2 rules —
    ``$HOME_NET any -> $EXTERNAL_NET $HTTP_PORTS``. The benign canary is RFC 1918 on both ends,
    so under Suricata's stock config (`EXTERNAL_NET: "!$HOME_NET"`) that rule can match nothing
    at all. Measured: stock config → 0 alerts, flabel's config → 1. Every abuse.ch label on an
    internal capture depends on this.
    """
    snapshot = make_snapshot(tmp_path, {"abuse.ch/feodotracker": [HOME_NET_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert [detection.sid for detection in detections] == [HOME_NET_SID], (
        "a $HOME_NET -> $EXTERNAL_NET rule did not fire on an internal-to-internal capture, "
        "which is what HOME_NET: any in flabel's own suricata.yaml exists to prevent"
    )


@pytest.mark.requires_tools
def test_synthetic_rule_yields_exactly_one_detection(tmp_path):
    """A rule matching the benign canary parses into one fully-populated `Detection`."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert len(detections) == 1
    detection = detections[0]

    assert detection.source == "et/open"
    assert detection.tier == 2
    assert (detection.sid, detection.rev) == (HTTP_SID, 3)
    # eve.json reports the classtype's *description* from Suricata's classification.config,
    # not the `trojan-activity` shortname. Asserted exactly so a change in what we record
    # cannot pass unnoticed.
    assert detection.classtype == "A Network Trojan was detected"
    assert detection.threat == "FLABEL TEST synthetic HTTP request"
    assert detection.app_proto == "http"
    assert detection.ts == pytest.approx(HTTP_ALERT_TS)
    assert (detection.src_ip, detection.src_port) == ("10.0.0.5", 49152)
    assert (detection.dst_ip, detection.dst_port) == ("10.0.0.200", 80)
    # Lowercase, because Zeek's conn.log writes `tcp` and correlation matches the two
    # 5-tuples field by field. Suricata reports `TCP`.
    assert detection.proto == "tcp"
    assert detection.metadata == (
        "confidence High",
        "created_at 2026_08_12",
        "signature_severity Major",
    )

    assert info.snapshot_id == snapshot_id_of(snapshot)
    assert info.alerts_total == 1
    assert info.identify_alerts_suppressed == 0
    assert info.rules_loaded == 1, "only the snapshot's one rule may load — no ambient ruleset"
    assert SEMVER.fullmatch(info.version), f"unparsed version {info.version!r}"

    # eve.json is a mixed stream — flow, http, fileinfo and stats records share it with
    # alerts. If the event_type filter were dropped, `alerts_total` would count those too.
    events = {
        json.loads(line)["event_type"]
        for line in (tmp_path / "out" / "eve.json").read_text().splitlines()
        if line.strip()
    }
    assert events > {"alert"}, f"eve.json held only alerts, so the filter proves nothing: {events}"


@pytest.mark.requires_tools
def test_ja4_rule_matches_a_tls_fixture(tmp_path):
    """A `ja4.hash` rule can produce a detection at all (US-14).

    ET Open 8.0 was measured to contain **zero** ``ja4.hash`` rules, so no real feed
    exercises this path. Without this test the JA4 labelling capability is unevidenced —
    the pipeline could ship unable to act on a JA4 rule and every other test would pass.
    """
    capture = tmp_path / "tls.pcap"
    write_tls_capture(capture)
    snapshot = make_snapshot(tmp_path, {"et/open": [JA4_SID]})

    detections, info = suricata.run_suricata(capture, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert len(detections) == 1, "the JA4 fingerprint rule did not match the ClientHello"
    detection = detections[0]
    assert detection.sid == JA4_SID
    assert detection.app_proto == "tls"
    assert (detection.src_ip, detection.src_port) == (TLS_CLIENT, TLS_SPORT)
    assert (detection.dst_ip, detection.dst_port) == (TLS_SERVER, 443)
    assert detection.ts == pytest.approx(TLS_BASE_TS + 0.03, abs=0.05)


@pytest.fixture
def half_hour_timezone(monkeypatch):
    """Run the test — and the Suricata it spawns — in a +05:30 timezone."""
    monkeypatch.setenv("TZ", "Asia/Kolkata")
    time.tzset()
    yield
    monkeypatch.undo()
    time.tzset()


@pytest.mark.requires_tools
def test_alert_timestamps_do_not_depend_on_the_local_timezone(tmp_path, half_hour_timezone):
    """`Detection.ts` is an absolute epoch value, whatever timezone the machine is in.

    Suricata writes eve timestamps in **local time with an offset**
    (``2023-11-15T03:43:20.050000+0530`` here). CI runs in UTC and a laptop does not, so an
    implementation that read the wall-clock part and ignored the offset would produce
    different timestamps for the same capture on different machines — a reproducibility break
    (Goal 2) that no other test in this file would notice, because they all run in one zone.
    A half-hour zone is used so an hours-only bug cannot pass either.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, _ = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections[0].ts == pytest.approx(HTTP_ALERT_TS)
    eve = (tmp_path / "out" / "eve.json").read_text()
    assert "+0530" in eve, "the fixture did not take effect, so nothing was proved"


@pytest.mark.requires_tools
def test_the_run_directory_holds_no_capture_content(tmp_path):
    """flabel processes other people's traffic; the run directory must not become a copy of it.

    Stock Suricata configurations commonly enable `file-store`, `pcap-log` or eve `payload`, any
    of which writes capture bytes to disk. flabel's own config disables all of them, and this
    asserts the *result* rather than trusting the YAML — it is also the list spec §10 needs for
    its reproducibility exclusions: `eve.json` (whose `stats` records are wall-clock) and
    `suricata.log` (wall-clock throughout, never reproducible).
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    outdir = tmp_path / "out"

    suricata.run_suricata(BENIGN, snapshot, outdir)

    assert sorted(path.name for path in outdir.iterdir()) == ["eve.json", "suricata.log"]
    records = [json.loads(line) for line in (outdir / "eve.json").read_text().splitlines() if line]
    assert {record["event_type"] for record in records} <= {"alert", "flow", "stats"}
    for record in records:
        assert "payload" not in record and "payload_printable" not in record
        assert "packet" not in record


@pytest.mark.requires_tools
def test_a_udp_detection_carries_the_tuple_zeek_will_have(tmp_path):
    """UDP, which the benign canary has none of and ET Open's DNS rules are full of.

    The values asserted are the ones Zeek writes for the same fixture (measured:
    ``10.0.0.9 53124 -> 10.0.0.204 53 udp``), because correlation compares the two field by
    field. Without this, nothing in step 6 evidences that a DNS detection can be matched at all.
    """
    capture = tmp_path / "mixed.pcap"
    write_mixed_capture(capture)
    snapshot = make_snapshot(tmp_path, {"et/open": [DNS_SID]})

    detections, info = suricata.run_suricata(capture, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert len(detections) == 1
    detection = detections[0]
    assert detection.proto == "udp"
    assert (detection.src_ip, detection.src_port) == (UDP_CLIENT, UDP_SPORT)
    assert (detection.dst_ip, detection.dst_port) == (UDP_SERVER, 53)
    assert detection.app_proto == "dns"


@pytest.mark.requires_tools
def test_icmp_detections_mirror_zeeks_port_columns(tmp_path):
    """ICMP has no ports, and `(0, 0)` would make every ICMP detection uncorrelatable.

    Zeek writes the ICMP type in `id.orig_p` and the counterpart type in `id.resp_p`; Suricata's
    alert record has `icmp_type`/`icmp_code` and no ports at all. Measured on this fixture —
    Zeek: ``icmp 8 -> 0`` for the v4 echo and ``icmp 128 -> 129`` for the v6 one; Suricata:
    ``icmp_type 8/128, icmp_code 0``. ET Open ships plenty of ICMP rules, and spec §9 fails the
    **whole run** above 1% unmatched, so three uncorrelatable ICMP alerts in 150 detections would
    be enough to lose every label in the run.

    The v6 case also pins the protocol name: Suricata says `IPv6-ICMP`, Zeek says `icmp`, and
    lowercasing alone would leave the two unable to ever match.
    """
    capture = tmp_path / "mixed.pcap"
    write_mixed_capture(capture)
    snapshot = make_snapshot(tmp_path, {"et/open": [ICMP_SID, ICMP6_SID]})

    detections, info = suricata.run_suricata(capture, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    by_sid = {detection.sid: detection for detection in detections}
    assert set(by_sid) == {ICMP_SID, ICMP6_SID}

    v4 = by_sid[ICMP_SID]
    assert v4.proto == "icmp"
    assert (v4.src_ip, v4.src_port) == (ICMP_CLIENT, 8), "ICMP type belongs in the source port"
    assert (v4.dst_ip, v4.dst_port) == (ICMP_SERVER, 0), "ICMP code belongs in the dest port"

    v6 = by_sid[ICMP6_SID]
    assert v6.proto == "icmp", "Zeek writes `icmp` for ICMPv6; `ipv6-icmp` could never match"
    # Compressed, as Zeek writes it. Suricata writes the expanded form, and correlation compares
    # the strings — so an unnormalised address makes every IPv6 detection unmatchable.
    assert (v6.src_ip, v6.dst_ip) == (ICMP6_CLIENT, ICMP6_SERVER)
    assert v6.src_port == 128


@pytest.mark.requires_tools
def test_identify_source_alert_is_suppressed(tmp_path):
    """An `identify` source's rule fires and produces no detection (spec §2.8, US-16).

    The rule matches; suppression happens on the *source class*, not on whether the rule was
    any good. Counted rather than dropped silently, because absence is never a signal
    (spec §2.5).
    """
    snapshot = make_snapshot(
        tmp_path, {"oisf/trafficid": [IDENTIFY_SID]}, {"oisf/trafficid": "identify"}
    )

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert detections == [], "an identify-class source may never produce a label"
    assert info.alerts_total == 1, "the rule must genuinely have fired for this to prove anything"
    assert info.identify_alerts_suppressed == 1


@pytest.mark.requires_tools
def test_suppression_is_per_source_not_per_run(tmp_path):
    """One snapshot, two sources: the labelling one survives, the `identify` one does not.

    This is what makes SID→source resolution load-bearing. Both rules match the same flow,
    so a resolver that attributed either alert to the wrong source would either lose a real
    detection or emit one it must never emit.
    """
    snapshot = make_snapshot(
        tmp_path,
        {"et/open": [HTTP_SID], "oisf/trafficid": [IDENTIFY_SID]},
        {"oisf/trafficid": "identify"},
    )

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert [(d.source, d.sid) for d in detections] == [("et/open", HTTP_SID)]
    assert info.rules_loaded == 2
    assert info.alerts_total == 2
    assert info.identify_alerts_suppressed == 1
    assert len(detections) == info.alerts_total - info.identify_alerts_suppressed


@pytest.mark.requires_tools
def test_a_capture_that_matches_nothing_is_an_empty_result_not_a_failure(tmp_path):
    """The case every failure path above exists to be distinguishable *from*.

    Rules loaded, capture read, nothing matched: no detections, no tool failure, and a
    non-zero `rules_loaded` to show the run genuinely looked. Without this pinned, a future
    "fail on zero alerts" would look reasonable and would break the ordinary case — and the
    benign canary (which must produce zero labels and still pass) depends on it.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [JA4_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert info.tool_failures == ()
    assert info.alerts_total == 0
    assert info.identify_alerts_suppressed == 0
    assert info.rules_loaded == 1


def test_attribution_comes_from_the_sid_index_not_from_raw_rule_text(tmp_path):
    """`sid_index.json` is the authority, and `raw/` is not read at all.

    Step 4 writes the map explicitly, so step 6 does not re-derive it: deriving source names from
    `raw/<source>.rules` paths invented an unwritten contract about multi-file feeds (ET Open is
    a tarball of many `.rules` files), and `raw/` is not covered by `snapshot_id`, so it could be
    edited without detection. A `raw/` tree that contradicts the index must change nothing.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    decoy = snapshot / "raw" / "somebody-elses-feed.rules"
    decoy.parent.mkdir(parents=True)
    decoy.write_text(RULES[HTTP_SID] + "\n" + RULES[IDENTIFY_SID] + "\n")

    index = suricata.sid_source_index(snapshot, suricata.load_manifest(snapshot))

    assert index == {HTTP_SID: "et/open"}


@pytest.mark.requires_tools
def test_two_runs_produce_the_same_alert_set(tmp_path):
    """Goal 2 as a whole-pass check: same input, same detections, same counts.

    Honest about its limits — with two rules over 14 packets, Suricata would very likely be
    deterministic without `--runmode single` too, so deleting that flag would not fail here.
    The flag itself is pinned by `test_argv_loads_only_the_snapshot_ruleset`; this test guards
    everything downstream of it, including the parse and the ordering of the returned list.
    """
    snapshot = make_snapshot(
        tmp_path,
        {"et/open": [HTTP_SID], "oisf/trafficid": [IDENTIFY_SID]},
        {"oisf/trafficid": "identify"},
    )

    first, first_info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "one")
    second, second_info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "two")

    assert first == second
    assert (first_info.alerts_total, first_info.identify_alerts_suppressed) == (
        second_info.alerts_total,
        second_info.identify_alerts_suppressed,
    )


# --- loss conditions (spec §11) ------------------------------------------------------------


def test_missing_binary_records_a_tool_failure(tmp_path, monkeypatch):
    """A Suricata that cannot be run at all is reported, not raised.

    Deliberately *not* marked ``requires_tools``: it works by emptying ``PATH``, so counting
    it toward "a tool test ran" would let a toolchain-less CI run look green (conftest.py).
    """
    monkeypatch.setenv("PATH", str(tmp_path / "empty"))
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    failure = info.tool_failures[0]
    assert failure.tool == "suricata"
    assert failure.exit_code is None
    assert "suricata" in failure.message
    assert info.snapshot_id == snapshot_id_of(snapshot), "provenance survives a tool failure"


@pytest.mark.requires_tools
def test_nonzero_exit_records_a_tool_failure(tmp_path):
    """Suricata exiting non-zero yields a `ToolFailure` and no detections."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(tmp_path / "absent.pcap", snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    failure = info.tool_failures[0]
    assert failure.tool == "suricata"
    assert failure.exit_code == 1
    assert "-S" in failure.argv, "the failing argv is recorded so the failure is reproducible"


@pytest.mark.requires_tools
def test_a_ruleset_the_engine_rejects_is_a_tool_failure(tmp_path):
    """Zero rules loaded is a failure, not an empty result.

    Suricata rejects a rule with an unknown keyword, then loads nothing, warns, and **exits
    0** (verified on 8.0.6). Nothing else in the run distinguishes that from a capture with
    no malicious traffic in it, which is exactly the shape spec §2.5 forbids.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [UNLOADABLE_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    assert info.tool_failures[0].exit_code == 0, "the point is that Suricata called this success"
    assert "loaded none" in info.tool_failures[0].message
    assert "1 failed" in info.tool_failures[0].message, "the engine's own count is reported"


@pytest.mark.requires_tools
def test_a_partial_rule_load_is_a_failure_not_a_thinner_run(tmp_path):
    """Some rules loaded, one rejected: the failure that actually happens with real feeds.

    A snapshot of two rules where one uses an unknown keyword loads *one*, alerts normally, and
    exits 0 — so the run looks complete while the labels the rejected rule would have produced
    are simply absent. 26 pawpatrules rules were measured failing to load against Suricata 8, so
    this is the ordinary case, not the exotic one.

    Hard failure by decision (Craig, 2026-08-12: record, warn above zero, fail above a
    threshold). The threshold half needs `rules_failed` on `SuricataRunInfo`, which does not
    exist yet, so for now any shortfall fails — the conservative half. **This will fail real runs
    until step 4 stops admitting rules this engine cannot load**, which is the intended alarm.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID, UNLOADABLE_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == [], "a partial ruleset must not produce labels that look complete"
    assert len(info.tool_failures) == 1
    message = info.tool_failures[0].message
    assert "loaded 1 of the snapshot's 2 rules" in message
    assert "1 failed" in message


def test_a_run_whose_rule_count_cannot_be_determined_fails(tmp_path):
    """ "We could not tell" is a third state, and it is not the same as zero.

    Both channels the count comes from — the eve stats record and `suricata.log` — are decided by
    configuration. If neither reports, the alert set cannot be attested against the snapshot at
    all, so it is not evidence. Kept distinct from the zero case, which has a different message
    and a different cause.
    """
    failure = suricata._check_ruleset_loaded(None, expected=3, argv=["suricata"], exit_code=0)

    assert failure is not None
    assert "no rule-load count" in failure.message

    agreed = suricata._check_ruleset_loaded((3, 0, 0), expected=3, argv=["suricata"], exit_code=0)
    assert agreed is None, "a ruleset that loaded in full is not a failure"


# --- eve.json parsing, unit-level -----------------------------------------------------------
#
# These reach for module-private helpers deliberately. Each covers a branch that only a
# malformed or hostile eve.json reaches, and no combination of real Suricata runs can produce
# one on demand — the alternative to testing them directly is not testing them.


def eve_file(path: Path, records: Sequence[object]) -> Path:
    """Write `records` as an eve.json-shaped stream of one JSON object per line."""
    path.write_text("".join(json.dumps(record) + "\n" for record in records))
    return path


def test_a_timestamp_without_an_offset_is_rejected(tmp_path):
    """A naive timestamp would be read as *local* time and shift silently by hours.

    `datetime.timestamp()` does that without erroring, so the same capture would yield
    different `ts` values on a UTC machine and a PDT one — the reproducibility break that
    `test_alert_timestamps_do_not_depend_on_the_local_timezone` proves does not happen when the
    offset is present.
    """
    with pytest.raises(ToolError, match="no UTC offset"):
        suricata._epoch("2023-11-14T14:13:20.050000", tmp_path / "eve.json", 1)


def test_an_unparseable_timestamp_is_rejected(tmp_path):
    with pytest.raises(ToolError, match="unparseable timestamp"):
        suricata._epoch("last tuesday", tmp_path / "eve.json", 1)


def test_a_malformed_eve_line_is_never_skipped(tmp_path):
    """A dropped record is a missing label, so an unreadable one fails the run."""
    path = tmp_path / "eve.json"
    path.write_text('{"event_type":"flow"}\n{"event_type":"alert"\n')

    with pytest.raises(ToolError, match="not valid JSON"):
        suricata._read_eve(path, {}, {})


def test_undecodable_bytes_become_a_flabel_error(tmp_path):
    """eve.json carries capture-derived strings, so invalid UTF-8 is a thing it can contain.

    It must surface as a `FlabelError` that `cli.py` can map to an exit code, not as a bare
    `UnicodeDecodeError` traceback.
    """
    path = tmp_path / "eve.json"
    path.write_bytes(b'{"event_type":"http","hostname":"\xff\xfe"}\n')

    with pytest.raises(ToolError, match="not valid UTF-8"):
        suricata._read_eve(path, {}, {})


def test_an_alert_without_a_signature_is_rejected(tmp_path):
    """`alert.signature` becomes `SourceEntry.threat`, which every label must carry."""
    path = eve_file(
        tmp_path / "eve.json",
        [{"event_type": "alert", "alert": {"signature_id": HTTP_SID, "rev": 1}}],
    )

    with pytest.raises(ToolError, match="alert.signature"):
        suricata._read_eve(path, {HTTP_SID: "et/open"}, {})


def test_an_alert_on_an_unattributable_sid_is_rejected(tmp_path):
    """Unreachable with `-S`, and still checked: the alternative is an invented origin."""
    path = eve_file(
        tmp_path / "eve.json",
        [{"event_type": "alert", "alert": {"signature_id": 4242, "signature": "x", "rev": 1}}],
    )

    with pytest.raises(SnapshotError, match="4242"):
        suricata._read_eve(path, {HTTP_SID: "et/open"}, {})


def test_a_decoy_sid_in_rule_content_is_not_read_as_the_rule_sid():
    """A rule whose `content:` contains ``sid:1;`` must still be attributed to its own SID.

    Otherwise every label from that rule names a different rule — and the SID it names may
    belong to a source with a different `source_class`.
    """
    rule = (
        'alert tcp any any -> any any (msg:"decoy"; content:"sid:1;"; '
        'pcre:"/sid:2;/"; classtype:trojan-activity; sid:9000123; rev:4;)'
    )

    assert suricata._sids([rule]) == {9000123}


def test_disabled_and_blank_rule_lines_carry_no_sids():
    """ET Open ships 19,479 `#alert` rules; none of them can fire, so none may be attributed."""
    lines = ["", "   ", "# a comment", f"#{RULES[HTTP_SID]}"]

    assert suricata._sids(lines) == set()


def test_all_three_rule_counts_are_read_from_the_log(tmp_path):
    """The fallback path, which no real run exercises while eve stats are on by default.

    All three counts come off one line. Reading only the loaded number — as this did at first —
    leaves the interesting one, `rules failed`, on the floor.
    """
    log = tmp_path / "suricata.log"
    log.write_text(
        "Info: detect: 3 rule files processed. 51752 rules successfully loaded, "
        "26 rules failed, 3 rules skipped\n"
    )

    assert suricata._rules_loaded_from_log(log) == (51752, 26, 3)
    assert suricata._rules_loaded_from_log(tmp_path / "absent.log") is None


def test_a_stats_record_reporting_zero_loaded_is_not_mistaken_for_silence():
    """Zero is an answer — every rule failed — and must not read as "stats said nothing"."""
    record = {"stats": {"detect": {"engines": [{"id": 0, "rules_loaded": 0, "rules_failed": 4}]}}}

    assert suricata._rules_loaded_from_stats(record) == (0, 4, 0)
    assert suricata._rules_loaded_from_stats({"stats": {"detect": {}}}) is None
    assert suricata._rules_loaded_from_stats({"stats": "not a dict"}) is None


def test_metadata_absent_or_malformed_is_empty_rather_than_an_error():
    """A rule with no `metadata:` is ordinary; only a *label* needs every field."""
    assert suricata._metadata(None) == ()
    assert suricata._metadata("confidence High") == ()
    assert suricata._metadata({"confidence": ["High"], "tag": "single"}) == (
        "confidence High",
        "tag single",
    )


# --- snapshot validation -------------------------------------------------------------------
#
# All of these run before any subprocess, so they need no toolchain. A snapshot that cannot
# support provenance is a hard failure (spec §7, §11): every one of these conditions would
# otherwise produce a run that looks clean and labels nothing, which is indistinguishable
# from a capture that contained nothing.


def test_missing_snapshot_directory_is_a_hard_failure(tmp_path):
    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, tmp_path / "nope", tmp_path / "out")


def test_missing_rules_file_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "rules.rules").unlink()

    with pytest.raises(SnapshotError, match="rules.rules"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_empty_rules_file_is_a_hard_failure(tmp_path):
    """Zero rules can never produce a label, and Suricata exits 0 having loaded none.

    Verified on 8.0.6: pointing ``-S`` at a missing or empty file is a *warning*, and the run
    completes successfully with an empty alert set. That is the most dangerous shape a bug
    can take here, so it is caught before the tool is invoked.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "rules.rules").write_text("# nothing admitted\n")
    reseal(snapshot)

    with pytest.raises(SnapshotError, match="no rules"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_missing_manifest_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "manifest.json").unlink()

    with pytest.raises(SnapshotError, match="manifest.json"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_unparseable_manifest_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "manifest.json").write_text("{not json")

    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_manifest_missing_a_field_is_a_hard_failure(tmp_path):
    """A manifest we cannot fully read cannot be trusted to say what may label."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    del document["sources"][0]["source_class"]
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match="source_class"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_manifest_with_an_unknown_source_class_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    document["sources"][0]["source_class"] = "probably-fine"
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_snapshot_without_a_sid_index_cannot_attribute_anything(tmp_path):
    """No `sid_index.json` means no SID→source mapping, and eve.json carries none either.

    Guessing would put a label's provenance — including whether its source may label at all —
    on nothing. Hard failure instead.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]}, sid_index=False)

    with pytest.raises(SnapshotError, match=SID_INDEX):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_an_unknown_sid_index_schema_is_a_hard_failure(tmp_path):
    """A format we do not understand is never read on a best-effort basis.

    The file decides which source each alert is attributed to, and therefore whether it may
    become a label at all — the one thing spec §13 calls absolute.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    set_sid_index(snapshot, {"et/open": [HTTP_SID]}, schema=2)

    with pytest.raises(SnapshotError, match="schema"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_sid_index_naming_a_source_the_manifest_does_not_list_is_a_hard_failure(tmp_path):
    """The manifest is the authority on which sources a snapshot contains.

    It is where `source_class` — hence `may_label` — comes from, so an attribution to a source it
    does not describe cannot be evaluated at all.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    set_sid_index(snapshot, {"somebody/else": [HTTP_SID]})

    with pytest.raises(SnapshotError, match="somebody/else"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_malformed_sid_index_entry_is_a_hard_failure(tmp_path):
    """A non-integer SID or a non-list of them would otherwise crash mid-parse."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / SID_INDEX).write_text(
        json.dumps({"schema": 1, "sources": {"et/open": ["9000001"]}})
    )
    reseal(snapshot)

    with pytest.raises(SnapshotError, match="non-integer"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_sid_claimed_by_two_sources_is_a_hard_failure(tmp_path):
    """Ambiguous attribution is never resolved by picking one.

    Kept a hard failure for now. Step 4 is adding a write-time collision check and measuring
    whether any of the nine feeds actually collide today; once that lands this should soften to
    match, because "rebuild the snapshot without the collision" is not a remedy an operator who
    does not control the upstream feeds can carry out.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID], "pawpatrules": [JA4_SID]})
    set_sid_index(snapshot, {"et/open": [HTTP_SID, JA4_SID], "pawpatrules": [JA4_SID]})

    with pytest.raises(SnapshotError, match=str(JA4_SID)):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_an_admitted_sid_no_source_claims_is_a_hard_failure(tmp_path):
    """A rule that could fire but could not be attributed fails the run up front."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    with (snapshot / "rules.rules").open("a") as handle:
        handle.write(RULES[JA4_SID].replace(f"sid:{JA4_SID};", "sid:9999999;") + "\n")
    reseal(snapshot)

    with pytest.raises(SnapshotError, match="9999999"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_an_attributed_sid_that_is_not_in_the_ruleset_is_a_hard_failure(tmp_path):
    """The other direction: the index describes rules that are not there.

    `rules.rules` is what Suricata reads, so if the two files disagree neither can be trusted to
    say what ran — and the snapshot id covers both, so this is a genuine inconsistency rather
    than drift.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    set_sid_index(snapshot, {"et/open": [HTTP_SID, 9999998]})

    with pytest.raises(SnapshotError, match="9999998"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_snapshot_id_that_does_not_hash_its_own_rules_is_a_hard_failure(tmp_path):
    """Spec §7 calls the id self-verifying, so it is actually verified.

    `snapshot_id` is read from `manifest.json` while the rules that fire come from
    `rules.rules`. Without this check, editing `rules.rules` leaves every label still claiming
    the original id — an origin that cannot be traced while looking perfectly traceable.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]}, snapshot_id=WRONG_SNAPSHOT_ID)

    with pytest.raises(SnapshotError, match="not internally consistent"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_edited_rules_invalidate_the_snapshot_id(tmp_path):
    """The same check from the other direction: a consistent snapshot, then tampered with."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    with (snapshot / "rules.rules").open("a") as handle:
        handle.write(RULES[IDENTIFY_SID] + "\n")

    with pytest.raises(SnapshotError, match="not internally consistent"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_duplicate_source_in_the_manifest_is_a_hard_failure(tmp_path):
    """Two entries of one name would make `may_label` depend on file order."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    shadow = dict(document["sources"][0], source_class="identify")
    document["sources"].append(shadow)
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match="more than once"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


@pytest.mark.parametrize(
    ("field", "value", "where"),
    [
        ("snapshot_id", 1234567890123456, "manifest"),
        ("created_at", 20260812, "manifest"),
        ("total_admitted", "one", "manifest"),
        ("name", 5, "source"),
        ("rules_admitted", "many", "source"),
        ("licence", None, "source"),
    ],
)
def test_a_manifest_field_of_the_wrong_type_is_a_hard_failure(tmp_path, field, value, where):
    """Presence is not enough — the type is checked too.

    JSON carries no schema, so `"snapshot_id": 1234567890123456` would otherwise construct a
    dataclass whose `str` field holds an int, and the failure would surface pages later as a bare
    `TypeError` or `AttributeError`. Those are not `FlabelError`s, so `cli.py` can only report
    them as a traceback rather than as a reason — the same bug class as the eve.json decode
    failure, one layer up.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    if where == "manifest":
        document[field] = value
    else:
        document["sources"][0][field] = value
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match=field):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_source_entry_that_is_not_an_object_is_a_hard_failure(tmp_path):
    """`"sources": [5]` used to reach the dataclass constructor as a bare `TypeError`."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    document["sources"] = [5]
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match="expected a JSON object"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_non_integer_signature_id_is_a_hard_failure(tmp_path):
    """`int(None)` raises `TypeError`, which `cli.py` could only print as a traceback."""
    path = eve_file(
        tmp_path / "eve.json",
        [{"event_type": "alert", "alert": {"signature_id": None, "signature": "x", "rev": 1}}],
    )

    with pytest.raises(ToolError, match="signature_id"):
        suricata._read_eve(path, {HTTP_SID: "et/open"}, {})


def test_an_unknown_manifest_field_is_tolerated(tmp_path):
    """Phase 2 must be additive (spec §2.7), so an unrecognised key is not fatal.

    The manifest is written by flabel, not by hand, so the `config.py` argument for rejecting
    unknown keys does not apply: rejecting them would mean a version that adds a field makes
    every snapshot already in `.flabel/rules/` unreadable.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    document["some_field_a_later_version_added"] = 7
    document["sources"][0]["another_one"] = "x"
    (snapshot / "manifest.json").write_text(json.dumps(document))

    manifest = suricata.load_manifest(snapshot)

    assert manifest.sources[0].name == "et/open"


def test_an_existing_eve_log_is_never_appended_to(tmp_path):
    """Suricata appends to ``eve.json``; a stale one would inject a previous run's alerts.

    Spec §13: never overwrite or modify a previous run directory.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    outdir = tmp_path / "out"
    outdir.mkdir()
    (outdir / "eve.json").write_text("")

    with pytest.raises(ToolError, match="eve.json"):
        suricata.run_suricata(BENIGN, snapshot, outdir)
