"""Suricata invocation and eve.json parsing (docs/spec.md §8, PLAN.md step 6).

Suricata is invoked for real here — the testing line is *tools real, network stubbed*
(spec §2), and a mock would encode our assumptions about the very tool behaviour that needs
verifying. Those tests carry ``@pytest.mark.requires_tools``. Nothing in this file makes a
network call or contacts a PANW device.

Two things are synthesized rather than sourced, both so the expected result is
*known-correct* rather than empirical:

* **the rules** — ``tests/fixtures/rules/synthetic.rules``, whose header explains why they
  avoid ``$HOME_NET``;
* **the snapshot** — a hand-built directory (``rules.rules`` + ``manifest.json`` +
  ``raw/<source>.rules``) rather than one written by ``rules/snapshot.py``, which lands in
  step 4 and is being built in parallel. That keeps this step independently testable, and
  the layout it builds is the one spec §7 documents.

The TLS capture for the JA4 test is generated into ``tmp_path`` rather than committed:
``tests/fixtures/`` has a deliberately narrow ``.gitignore`` exception, and a capture that
can be regenerated byte-for-byte does not need to live in git.
"""

from __future__ import annotations

import dataclasses
import hashlib
import importlib.util
import json
import re
import struct
import time
from collections.abc import Mapping, Sequence
from pathlib import Path

import pytest

from flabel import suricata
from flabel.errors import SnapshotError, ToolError
from flabel.models import SnapshotManifest, SourceAdmission

FIXTURES = Path(__file__).resolve().parent / "fixtures"
BENIGN = FIXTURES / "benign.pcap"
SYNTHETIC_RULES = FIXTURES / "rules" / "synthetic.rules"

#: SIDs in ``synthetic.rules``; see that file for what each one matches.
HTTP_SID = 9000001
JA4_SID = 9000002
IDENTIFY_SID = 9000003
UNLOADABLE_SID = 9000004

#: A well-formed id that is not the hash of anything, for injecting an inconsistent snapshot.
WRONG_SNAPSHOT_ID = "0123456789abcdef"

#: The alert timestamp the HTTP rule must carry: ``make_canary.BASE_TS`` + 0.05s. The canary's
#: first flow runs one packet every 0.01s and the request is its 4th; Suricata raises the alert
#: on the 6th (``pcap_cnt`` 6), when the stream has been reassembled — i.e. on the packet
#: Suricata was looking at, not the one carrying the bytes. Asserted as an absolute epoch value
#: because correlation joins it against Zeek's epoch ``ts`` (spec §9).
HTTP_ALERT_TS = 1700000000.05

SEMVER = re.compile(r"\d+\.\d+\.\d+")


# --- fixture generators -------------------------------------------------------------------


def _load_canary() -> object:
    """Load ``make_canary.py`` as a module for its packet-building helpers.

    Imported rather than re-implemented: its IP/TCP checksum code is already verified
    against Zeek and Suricata, and a capture with a wrong checksum is exactly the kind of
    fixture that fails in a way no assertion explains. It is a fixture generator, not
    library code, hence the explicit file load.
    """
    spec = importlib.util.spec_from_file_location("flabel_make_canary", FIXTURES / "make_canary.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


CANARY = _load_canary()

TLS_CLIENT = "10.0.0.7"
TLS_SERVER = "10.0.0.202"
TLS_SPORT = 49200
TLS_BASE_TS = 1700000100.0


def _extension(kind: int, body: bytes) -> bytes:
    return struct.pack("!HH", kind, len(body)) + body


def _client_hello() -> bytes:
    """A TLS 1.3 ClientHello whose JA4_a segment is ``t13d0405h2``.

    Fixed content — including the 32 "random" bytes — so the JA4 value is identical on every
    run: TCP, TLS 1.3 (from ``supported_versions``), SNI present, 4 ciphers, 5 extensions,
    first ALPN ``h2``. That is what ``synthetic.rules`` sid 9000002 matches on.
    """
    host = b"flabel.test"
    server_name = _extension(0x0000, struct.pack("!HBH", len(host) + 3, 0, len(host)) + host)
    supported_groups = _extension(0x000A, struct.pack("!HH", 2, 0x001D))
    signature_algorithms = _extension(0x000D, struct.pack("!HHHH", 6, 0x0403, 0x0804, 0x0401))
    alpn_body = b"\x02h2"
    alpn = _extension(0x0010, struct.pack("!H", len(alpn_body)) + alpn_body)
    supported_versions = _extension(0x002B, struct.pack("!BHH", 4, 0x0304, 0x0303))
    extensions = server_name + supported_groups + signature_algorithms + alpn + supported_versions

    ciphers = struct.pack("!HHHH", 0x1301, 0x1302, 0x1303, 0xC02F)
    body = (
        struct.pack("!H", 0x0303)
        + bytes(range(32))
        + b"\x00"  # no session id
        + struct.pack("!H", len(ciphers))
        + ciphers
        + b"\x01\x00"  # compression: null only
        + struct.pack("!H", len(extensions))
        + extensions
    )
    handshake = b"\x01" + len(body).to_bytes(3, "big") + body
    return b"\x16\x03\x01" + struct.pack("!H", len(handshake)) + handshake


def write_tls_capture(path: Path) -> None:
    """One TCP flow to port 443 carrying the ClientHello above, byte-deterministic."""
    hello = _client_hello()
    client_seq, server_seq = 2000, 7000
    steps = [
        (TLS_CLIENT, TLS_SERVER, TLS_SPORT, 443, client_seq, 0, CANARY.SYN, b""),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq,
            client_seq + 1,
            CANARY.SYN | CANARY.ACK,
            b"",
        ),
        (TLS_CLIENT, TLS_SERVER, TLS_SPORT, 443, client_seq + 1, server_seq + 1, CANARY.ACK, b""),
        (
            TLS_CLIENT,
            TLS_SERVER,
            TLS_SPORT,
            443,
            client_seq + 1,
            server_seq + 1,
            CANARY.PSH | CANARY.ACK,
            hello,
        ),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq + 1,
            client_seq + 1 + len(hello),
            CANARY.ACK,
            b"",
        ),
        (
            TLS_CLIENT,
            TLS_SERVER,
            TLS_SPORT,
            443,
            client_seq + 1 + len(hello),
            server_seq + 1,
            CANARY.FIN | CANARY.ACK,
            b"",
        ),
        (
            TLS_SERVER,
            TLS_CLIENT,
            443,
            TLS_SPORT,
            server_seq + 1,
            client_seq + 2 + len(hello),
            CANARY.FIN | CANARY.ACK,
            b"",
        ),
    ]

    packets = []
    for index, (src, dst, sport, dport, seq, ack, flags, payload) in enumerate(steps):
        segment = CANARY.tcp(sport, dport, seq, ack, flags, src, dst, payload)
        frame = CANARY.ethernet(CANARY.ipv4(src, dst, segment, ident=500 + index))
        packets.append((TLS_BASE_TS + index * 0.01, frame))
    CANARY.write_pcap(str(path), packets)


def rule_lines() -> dict[int, str]:
    """The synthetic rules, keyed by SID."""
    lines = {}
    for line in SYNTHETIC_RULES.read_text(encoding="utf-8").splitlines():
        if not line.startswith("alert"):
            continue
        match = re.search(r"\bsid:(\d+);", line)
        assert match is not None, f"synthetic rule has no sid: {line}"
        lines[int(match.group(1))] = line
    return lines


RULES = rule_lines()


def make_snapshot(
    root: Path,
    contents: Mapping[str, Sequence[int]],
    classes: Mapping[str, str] | None = None,
    *,
    raw: bool = True,
    extra_raw: Mapping[str, Sequence[int]] | None = None,
    snapshot_id: str | None = None,
) -> Path:
    """Hand-build the snapshot layout of spec §7 from `contents` (source name → SIDs).

    Stands in for step 4's ``write_snapshot`` so this step stays independently testable.
    ``raw=False`` omits the per-source rule files, which is how the "this snapshot cannot
    attribute its SIDs" failure is injected. ``extra_raw`` adds SIDs to a source's ``raw/``
    file *without* admitting them — which is what as-fetched text really looks like, since
    admission rejects most of it.

    `snapshot_id` defaults to the real ``sha256(rules.rules)[:16]`` that spec §7 defines, so
    fixtures are internally consistent the way a written snapshot is; pass a string to inject
    an id that does not match its own rules.
    """
    classes = classes or {}
    extra_raw = extra_raw or {}
    snapshot = root / "snapshot"
    snapshot.mkdir(parents=True, exist_ok=True)

    admissions = []
    admitted: list[str] = []
    for name in sorted(contents):
        lines = [RULES[sid] for sid in sorted(contents[name])]
        admitted.extend(lines)
        if raw:
            raw_path = snapshot / "raw" / f"{name}.rules"
            raw_path.parent.mkdir(parents=True, exist_ok=True)
            fetched = lines + [RULES[sid] for sid in sorted(extra_raw.get(name, ()))]
            # A comment line and a blank line, because raw text is "as fetched" and real
            # feeds ship both — the SID scan must skip them.
            raw_path.write_text(f"# {name} as fetched\n\n" + "\n".join(fetched) + "\n")
        admissions.append(
            SourceAdmission(
                name=name,
                url=f"https://example.invalid/{name}.rules",
                licence="MIT",
                source_class=classes.get(name, "signature"),
                admission_basis="wholesale",
                rules_fetched=len(lines),
                rules_admitted=len(lines),
                rules_excluded_no_confidence=0,
                rules_excluded_low_confidence=0,
                rules_excluded_low_severity=0,
                rules_excluded_commented=0,
                ja4_rules_admitted=sum("ja4.hash" in line for line in lines),
                ja3_rules_admitted=0,
                fetched_at="2026-08-12T00:00:00.000000Z",
            )
        )

    rules = snapshot / "rules.rules"
    rules.write_text("\n".join(admitted) + "\n" if admitted else "")
    manifest = SnapshotManifest(
        snapshot_id=snapshot_id or hashlib.sha256(rules.read_bytes()).hexdigest()[:16],
        created_at="2026-08-12T00:00:00.000000Z",
        flabel_version="0.0.0",
        sources=tuple(admissions),
        total_admitted=len(admitted),
        total_ja4_admitted=sum(admission.ja4_rules_admitted for admission in admissions),
    )
    (snapshot / "manifest.json").write_text(json.dumps(dataclasses.asdict(manifest), indent=2))
    return snapshot


def snapshot_id_of(snapshot: Path) -> str:
    """The id the manifest claims, read the way `provenance` will read it."""
    return json.loads((snapshot / "manifest.json").read_text())["snapshot_id"]


def reseal(snapshot: Path) -> None:
    """Recompute `snapshot_id` after a test has rewritten ``rules.rules``.

    Needed because the id is verified against the file's hash: without this, every test that
    injects a *rules* fault would trip the consistency check first and prove nothing about the
    fault it meant to inject.
    """
    document = json.loads((snapshot / "manifest.json").read_text())
    digest = hashlib.sha256((snapshot / "rules.rules").read_bytes()).hexdigest()
    document["snapshot_id"] = digest[:16]
    (snapshot / "manifest.json").write_text(json.dumps(document, indent=2))


# --- the invocation itself -----------------------------------------------------------------


def test_argv_loads_only_the_snapshot_ruleset():
    """The flags of spec §8, asserted as a contract rather than trusted to a comment.

    ``-S`` *replaces* the ruleset; ``-s`` would *add* to whatever the system config already
    loads. Getting that wrong is invisible in the output — labels would silently carry SIDs
    from rules that are in no snapshot, i.e. a verdict whose origin cannot be traced
    (spec §13). Same reasoning as step 5's regression test on Zeek's ``-D``.
    """
    argv = suricata.build_argv(Path("/tmp/cap.pcap"), Path("/snap"), Path("/out"))

    assert argv[0] == "suricata"
    assert argv[argv.index("-r") + 1] == "/tmp/cap.pcap"
    assert argv[argv.index("-l") + 1] == "/out"
    assert argv[argv.index("-S") + 1] == "/snap/rules.rules"
    assert "-s" not in argv, "-s adds to the system ruleset; only -S replaces it"
    assert "--rule-reload" not in argv
    assert argv[argv.index("--runmode") + 1] == "single"
    assert "--set" in argv
    assert "app-layer.protocols.tls.ja3-fingerprints=yes" in argv
    assert "app-layer.protocols.tls.ja4-fingerprints=yes" in argv


@pytest.mark.requires_tools
def test_synthetic_rule_yields_exactly_one_detection(tmp_path):
    """A rule matching the benign canary parses into one fully-populated `Detection`."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert len(detections) == 1
    detection = detections[0]

    assert detection.source == "et/open"
    assert detection.tier == 2
    assert (detection.sid, detection.rev) == (HTTP_SID, 3)
    # eve.json reports the classtype's *description* from Suricata's classification.config,
    # not the `trojan-activity` shortname. Asserted exactly so a change in what we record
    # cannot pass unnoticed.
    assert detection.classtype == "A Network Trojan was detected"
    assert detection.threat == "FLABEL TEST synthetic HTTP request"
    assert detection.app_proto == "http"
    assert detection.ts == pytest.approx(HTTP_ALERT_TS)
    assert (detection.src_ip, detection.src_port) == ("10.0.0.5", 49152)
    assert (detection.dst_ip, detection.dst_port) == ("10.0.0.200", 80)
    # Lowercase, because Zeek's conn.log writes `tcp` and correlation matches the two
    # 5-tuples field by field. Suricata reports `TCP`.
    assert detection.proto == "tcp"
    assert detection.metadata == (
        "confidence High",
        "created_at 2026_08_12",
        "signature_severity Major",
    )

    assert info.snapshot_id == snapshot_id_of(snapshot)
    assert info.alerts_total == 1
    assert info.identify_alerts_suppressed == 0
    assert info.rules_loaded == 1, "only the snapshot's one rule may load — no ambient ruleset"
    assert SEMVER.fullmatch(info.version), f"unparsed version {info.version!r}"

    # eve.json is a mixed stream — flow, http, fileinfo and stats records share it with
    # alerts. If the event_type filter were dropped, `alerts_total` would count those too.
    events = {
        json.loads(line)["event_type"]
        for line in (tmp_path / "out" / "eve.json").read_text().splitlines()
        if line.strip()
    }
    assert events > {"alert"}, f"eve.json held only alerts, so the filter proves nothing: {events}"


@pytest.mark.requires_tools
def test_ja4_rule_matches_a_tls_fixture(tmp_path):
    """A `ja4.hash` rule can produce a detection at all (US-14).

    ET Open 8.0 was measured to contain **zero** ``ja4.hash`` rules, so no real feed
    exercises this path. Without this test the JA4 labelling capability is unevidenced —
    the pipeline could ship unable to act on a JA4 rule and every other test would pass.
    """
    capture = tmp_path / "tls.pcap"
    write_tls_capture(capture)
    snapshot = make_snapshot(tmp_path, {"et/open": [JA4_SID]})

    detections, info = suricata.run_suricata(capture, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert len(detections) == 1, "the JA4 fingerprint rule did not match the ClientHello"
    detection = detections[0]
    assert detection.sid == JA4_SID
    assert detection.app_proto == "tls"
    assert (detection.src_ip, detection.src_port) == (TLS_CLIENT, TLS_SPORT)
    assert (detection.dst_ip, detection.dst_port) == (TLS_SERVER, 443)
    assert detection.ts == pytest.approx(TLS_BASE_TS + 0.03, abs=0.05)


@pytest.fixture
def half_hour_timezone(monkeypatch):
    """Run the test — and the Suricata it spawns — in a +05:30 timezone."""
    monkeypatch.setenv("TZ", "Asia/Kolkata")
    time.tzset()
    yield
    monkeypatch.undo()
    time.tzset()


@pytest.mark.requires_tools
def test_alert_timestamps_do_not_depend_on_the_local_timezone(tmp_path, half_hour_timezone):
    """`Detection.ts` is an absolute epoch value, whatever timezone the machine is in.

    Suricata writes eve timestamps in **local time with an offset**
    (``2023-11-15T03:43:20.050000+0530`` here). CI runs in UTC and a laptop does not, so an
    implementation that read the wall-clock part and ignored the offset would produce
    different timestamps for the same capture on different machines — a reproducibility break
    (Goal 2) that no other test in this file would notice, because they all run in one zone.
    A half-hour zone is used so an hours-only bug cannot pass either.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, _ = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections[0].ts == pytest.approx(HTTP_ALERT_TS)
    eve = (tmp_path / "out" / "eve.json").read_text()
    assert "+0530" in eve, "the fixture did not take effect, so nothing was proved"


@pytest.mark.requires_tools
def test_identify_source_alert_is_suppressed(tmp_path):
    """An `identify` source's rule fires and produces no detection (spec §2.8, US-16).

    The rule matches; suppression happens on the *source class*, not on whether the rule was
    any good. Counted rather than dropped silently, because absence is never a signal
    (spec §2.5).
    """
    snapshot = make_snapshot(
        tmp_path, {"oisf/trafficid": [IDENTIFY_SID]}, {"oisf/trafficid": "identify"}
    )

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert detections == [], "an identify-class source may never produce a label"
    assert info.alerts_total == 1, "the rule must genuinely have fired for this to prove anything"
    assert info.identify_alerts_suppressed == 1


@pytest.mark.requires_tools
def test_suppression_is_per_source_not_per_run(tmp_path):
    """One snapshot, two sources: the labelling one survives, the `identify` one does not.

    This is what makes SID→source resolution load-bearing. Both rules match the same flow,
    so a resolver that attributed either alert to the wrong source would either lose a real
    detection or emit one it must never emit.
    """
    snapshot = make_snapshot(
        tmp_path,
        {"et/open": [HTTP_SID], "oisf/trafficid": [IDENTIFY_SID]},
        {"oisf/trafficid": "identify"},
    )

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert info.tool_failures == ()
    assert [(d.source, d.sid) for d in detections] == [("et/open", HTTP_SID)]
    assert info.rules_loaded == 2
    assert info.alerts_total == 2
    assert info.identify_alerts_suppressed == 1
    assert len(detections) == info.alerts_total - info.identify_alerts_suppressed


@pytest.mark.requires_tools
def test_a_capture_that_matches_nothing_is_an_empty_result_not_a_failure(tmp_path):
    """The case every failure path above exists to be distinguishable *from*.

    Rules loaded, capture read, nothing matched: no detections, no tool failure, and a
    non-zero `rules_loaded` to show the run genuinely looked. Without this pinned, a future
    "fail on zero alerts" would look reasonable and would break the ordinary case — and the
    benign canary (which must produce zero labels and still pass) depends on it.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [JA4_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert info.tool_failures == ()
    assert info.alerts_total == 0
    assert info.identify_alerts_suppressed == 0
    assert info.rules_loaded == 1


@pytest.mark.requires_tools
def test_rules_present_in_raw_but_not_admitted_are_ignored(tmp_path):
    """`raw/` is the text *as fetched*, so attribution intersects it with what was admitted.

    A rule admission rejected sits in `raw/` and is not in `rules.rules`. It can never fire,
    so it must not make its SID look attributable — and must not be mistaken for a SID the
    snapshot admits but cannot trace.
    """
    snapshot = make_snapshot(
        tmp_path, {"et/open": [HTTP_SID]}, extra_raw={"et/open": [IDENTIFY_SID, JA4_SID]}
    )

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert [detection.sid for detection in detections] == [HTTP_SID]
    assert info.rules_loaded == 1, "only the admitted rule may load, never the raw text"
    assert suricata.sid_source_index(snapshot, suricata.load_manifest(snapshot)) == {
        HTTP_SID: "et/open"
    }


@pytest.mark.requires_tools
def test_two_runs_produce_the_same_alert_set(tmp_path):
    """Goal 2 as a whole-pass check: same input, same detections, same counts.

    Honest about its limits — with two rules over 14 packets, Suricata would very likely be
    deterministic without `--runmode single` too, so deleting that flag would not fail here.
    The flag itself is pinned by `test_argv_loads_only_the_snapshot_ruleset`; this test guards
    everything downstream of it, including the parse and the ordering of the returned list.
    """
    snapshot = make_snapshot(
        tmp_path,
        {"et/open": [HTTP_SID], "oisf/trafficid": [IDENTIFY_SID]},
        {"oisf/trafficid": "identify"},
    )

    first, first_info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "one")
    second, second_info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "two")

    assert first == second
    assert (first_info.alerts_total, first_info.identify_alerts_suppressed) == (
        second_info.alerts_total,
        second_info.identify_alerts_suppressed,
    )


# --- loss conditions (spec §11) ------------------------------------------------------------


def test_missing_binary_records_a_tool_failure(tmp_path, monkeypatch):
    """A Suricata that cannot be run at all is reported, not raised.

    Deliberately *not* marked ``requires_tools``: it works by emptying ``PATH``, so counting
    it toward "a tool test ran" would let a toolchain-less CI run look green (conftest.py).
    """
    monkeypatch.setenv("PATH", str(tmp_path / "empty"))
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    failure = info.tool_failures[0]
    assert failure.tool == "suricata"
    assert failure.exit_code is None
    assert "suricata" in failure.message
    assert info.snapshot_id == snapshot_id_of(snapshot), "provenance survives a tool failure"


@pytest.mark.requires_tools
def test_nonzero_exit_records_a_tool_failure(tmp_path):
    """Suricata exiting non-zero yields a `ToolFailure` and no detections."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})

    detections, info = suricata.run_suricata(tmp_path / "absent.pcap", snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    failure = info.tool_failures[0]
    assert failure.tool == "suricata"
    assert failure.exit_code == 1
    assert "-S" in failure.argv, "the failing argv is recorded so the failure is reproducible"


@pytest.mark.requires_tools
def test_a_ruleset_the_engine_rejects_is_a_tool_failure(tmp_path):
    """Zero rules loaded is a failure, not an empty result.

    Suricata rejects a rule with an unknown keyword, then loads nothing, warns, and **exits
    0** (verified on 8.0.6). Nothing else in the run distinguishes that from a capture with
    no malicious traffic in it, which is exactly the shape spec §2.5 forbids.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [UNLOADABLE_SID]})

    detections, info = suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")

    assert detections == []
    assert len(info.tool_failures) == 1
    assert info.tool_failures[0].exit_code == 0, "the point is that Suricata called this success"
    assert "no rules" in info.tool_failures[0].message


# --- eve.json parsing, unit-level -----------------------------------------------------------
#
# These reach for module-private helpers deliberately. Each covers a branch that only a
# malformed or hostile eve.json reaches, and no combination of real Suricata runs can produce
# one on demand — the alternative to testing them directly is not testing them.


def eve_file(path: Path, records: Sequence[object]) -> Path:
    """Write `records` as an eve.json-shaped stream of one JSON object per line."""
    path.write_text("".join(json.dumps(record) + "\n" for record in records))
    return path


def test_a_timestamp_without_an_offset_is_rejected(tmp_path):
    """A naive timestamp would be read as *local* time and shift silently by hours.

    `datetime.timestamp()` does that without erroring, so the same capture would yield
    different `ts` values on a UTC machine and a PDT one — the reproducibility break that
    `test_alert_timestamps_do_not_depend_on_the_local_timezone` proves does not happen when the
    offset is present.
    """
    with pytest.raises(ToolError, match="no UTC offset"):
        suricata._epoch("2023-11-14T14:13:20.050000", tmp_path / "eve.json", 1)


def test_an_unparseable_timestamp_is_rejected(tmp_path):
    with pytest.raises(ToolError, match="unparseable timestamp"):
        suricata._epoch("last tuesday", tmp_path / "eve.json", 1)


def test_a_malformed_eve_line_is_never_skipped(tmp_path):
    """A dropped record is a missing label, so an unreadable one fails the run."""
    path = tmp_path / "eve.json"
    path.write_text('{"event_type":"flow"}\n{"event_type":"alert"\n')

    with pytest.raises(ToolError, match="not valid JSON"):
        suricata._read_eve(path, {}, {})


def test_undecodable_bytes_become_a_flabel_error(tmp_path):
    """eve.json carries capture-derived strings, so invalid UTF-8 is a thing it can contain.

    It must surface as a `FlabelError` that `cli.py` can map to an exit code, not as a bare
    `UnicodeDecodeError` traceback.
    """
    path = tmp_path / "eve.json"
    path.write_bytes(b'{"event_type":"http","hostname":"\xff\xfe"}\n')

    with pytest.raises(ToolError, match="not valid UTF-8"):
        suricata._read_eve(path, {}, {})


def test_an_alert_without_a_signature_is_rejected(tmp_path):
    """`alert.signature` becomes `SourceEntry.threat`, which every label must carry."""
    path = eve_file(
        tmp_path / "eve.json",
        [{"event_type": "alert", "alert": {"signature_id": HTTP_SID, "rev": 1}}],
    )

    with pytest.raises(ToolError, match="alert.signature"):
        suricata._read_eve(path, {HTTP_SID: "et/open"}, {})


def test_an_alert_on_an_unattributable_sid_is_rejected(tmp_path):
    """Unreachable with `-S`, and still checked: the alternative is an invented origin."""
    path = eve_file(
        tmp_path / "eve.json",
        [{"event_type": "alert", "alert": {"signature_id": 4242, "signature": "x", "rev": 1}}],
    )

    with pytest.raises(SnapshotError, match="4242"):
        suricata._read_eve(path, {HTTP_SID: "et/open"}, {})


def test_a_decoy_sid_in_rule_content_is_not_read_as_the_rule_sid():
    """A rule whose `content:` contains ``sid:1;`` must still be attributed to its own SID.

    Otherwise every label from that rule names a different rule — and the SID it names may
    belong to a source with a different `source_class`.
    """
    rule = (
        'alert tcp any any -> any any (msg:"decoy"; content:"sid:1;"; '
        'pcre:"/sid:2;/"; classtype:trojan-activity; sid:9000123; rev:4;)'
    )

    assert suricata._sids([rule]) == {9000123}


def test_disabled_and_blank_rule_lines_carry_no_sids():
    """ET Open ships 19,479 `#alert` rules; none of them can fire, so none may be attributed."""
    lines = ["", "   ", "# a comment", f"#{RULES[HTTP_SID]}"]

    assert suricata._sids(lines) == set()


def test_rules_loaded_is_read_from_the_log_when_stats_are_absent(tmp_path):
    """The fallback path, which no real run exercises while eve stats are on by default."""
    log = tmp_path / "suricata.log"
    log.write_text(
        "Info: detect: 3 rule files processed. 51778 rules successfully loaded, "
        "0 rules failed, 0 rules skipped\n"
    )

    assert suricata._rules_loaded_from_log(log) == 51778
    assert suricata._rules_loaded_from_log(tmp_path / "absent.log") is None


def test_a_stats_record_reporting_zero_loaded_is_not_mistaken_for_silence():
    """Zero is an answer — every rule failed — and must not read as "stats said nothing"."""
    record = {"stats": {"detect": {"engines": [{"id": 0, "rules_loaded": 0}]}}}

    assert suricata._rules_loaded_from_stats(record) == 0
    assert suricata._rules_loaded_from_stats({"stats": {"detect": {}}}) is None
    assert suricata._rules_loaded_from_stats({"stats": "not a dict"}) is None


def test_metadata_absent_or_malformed_is_empty_rather_than_an_error():
    """A rule with no `metadata:` is ordinary; only a *label* needs every field."""
    assert suricata._metadata(None) == ()
    assert suricata._metadata("confidence High") == ()
    assert suricata._metadata({"confidence": ["High"], "tag": "single"}) == (
        "confidence High",
        "tag single",
    )


# --- snapshot validation -------------------------------------------------------------------
#
# All of these run before any subprocess, so they need no toolchain. A snapshot that cannot
# support provenance is a hard failure (spec §7, §11): every one of these conditions would
# otherwise produce a run that looks clean and labels nothing, which is indistinguishable
# from a capture that contained nothing.


def test_missing_snapshot_directory_is_a_hard_failure(tmp_path):
    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, tmp_path / "nope", tmp_path / "out")


def test_missing_rules_file_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "rules.rules").unlink()

    with pytest.raises(SnapshotError, match="rules.rules"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_empty_rules_file_is_a_hard_failure(tmp_path):
    """Zero rules can never produce a label, and Suricata exits 0 having loaded none.

    Verified on 8.0.6: pointing ``-S`` at a missing or empty file is a *warning*, and the run
    completes successfully with an empty alert set. That is the most dangerous shape a bug
    can take here, so it is caught before the tool is invoked.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "rules.rules").write_text("# nothing admitted\n")
    reseal(snapshot)

    with pytest.raises(SnapshotError, match="no rules"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_missing_manifest_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "manifest.json").unlink()

    with pytest.raises(SnapshotError, match="manifest.json"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_unparseable_manifest_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "manifest.json").write_text("{not json")

    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_manifest_missing_a_field_is_a_hard_failure(tmp_path):
    """A manifest we cannot fully read cannot be trusted to say what may label."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    del document["sources"][0]["source_class"]
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match="source_class"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_manifest_with_an_unknown_source_class_is_a_hard_failure(tmp_path):
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    document["sources"][0]["source_class"] = "probably-fine"
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_snapshot_without_per_source_rules_cannot_attribute_sids(tmp_path):
    """No ``raw/`` means no SID→source mapping, and eve.json carries none either.

    Guessing would put a label's provenance — including whether its source may label at all —
    on nothing. Hard failure instead.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]}, raw=False)

    with pytest.raises(SnapshotError, match="raw"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_sid_claimed_by_two_sources_is_a_hard_failure(tmp_path):
    """Ambiguous attribution is never resolved by picking one."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID], "pawpatrules": [HTTP_SID]})

    with pytest.raises(SnapshotError, match=str(HTTP_SID)):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_an_admitted_sid_no_source_claims_is_a_hard_failure(tmp_path):
    """A rule that could fire but could not be attributed fails the run up front."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    with (snapshot / "rules.rules").open("a") as handle:
        handle.write(RULES[JA4_SID].replace(f"sid:{JA4_SID};", "sid:9999999;") + "\n")
    reseal(snapshot)

    with pytest.raises(SnapshotError, match="9999999"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_raw_rules_for_a_source_absent_from_the_manifest_is_a_hard_failure(tmp_path):
    """The manifest is the authority on which sources are in a snapshot.

    A ``raw/`` file the manifest does not mention means the two disagree, and the manifest is
    where ``source_class`` — hence `may_label` — comes from.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    (snapshot / "raw" / "mystery.rules").write_text(RULES[JA4_SID] + "\n")

    with pytest.raises(SnapshotError, match="mystery"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_snapshot_id_that_does_not_hash_its_own_rules_is_a_hard_failure(tmp_path):
    """Spec §7 calls the id self-verifying, so it is actually verified.

    `snapshot_id` is read from `manifest.json` while the rules that fire come from
    `rules.rules`. Without this check, editing `rules.rules` leaves every label still claiming
    the original id — an origin that cannot be traced while looking perfectly traceable.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]}, snapshot_id=WRONG_SNAPSHOT_ID)

    with pytest.raises(SnapshotError, match="not internally consistent"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_edited_rules_invalidate_the_snapshot_id(tmp_path):
    """The same check from the other direction: a consistent snapshot, then tampered with."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    with (snapshot / "rules.rules").open("a") as handle:
        handle.write(RULES[IDENTIFY_SID] + "\n")

    with pytest.raises(SnapshotError, match="not internally consistent"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_a_duplicate_source_in_the_manifest_is_a_hard_failure(tmp_path):
    """Two entries of one name would make `may_label` depend on file order."""
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    shadow = dict(document["sources"][0], source_class="identify")
    document["sources"].append(shadow)
    (snapshot / "manifest.json").write_text(json.dumps(document))

    with pytest.raises(SnapshotError, match="more than once"):
        suricata.run_suricata(BENIGN, snapshot, tmp_path / "out")


def test_an_unknown_manifest_field_is_tolerated(tmp_path):
    """Phase 2 must be additive (spec §2.7), so an unrecognised key is not fatal.

    The manifest is written by flabel, not by hand, so the `config.py` argument for rejecting
    unknown keys does not apply: rejecting them would mean a version that adds a field makes
    every snapshot already in `.flabel/rules/` unreadable.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    document = json.loads((snapshot / "manifest.json").read_text())
    document["some_field_a_later_version_added"] = 7
    document["sources"][0]["another_one"] = "x"
    (snapshot / "manifest.json").write_text(json.dumps(document))

    manifest = suricata.load_manifest(snapshot)

    assert manifest.sources[0].name == "et/open"


def test_an_existing_eve_log_is_never_appended_to(tmp_path):
    """Suricata appends to ``eve.json``; a stale one would inject a previous run's alerts.

    Spec §13: never overwrite or modify a previous run directory.
    """
    snapshot = make_snapshot(tmp_path, {"et/open": [HTTP_SID]})
    outdir = tmp_path / "out"
    outdir.mkdir()
    (outdir / "eve.json").write_text("")

    with pytest.raises(ToolError, match="eve.json"):
        suricata.run_suricata(BENIGN, snapshot, outdir)
