"""Generate the awkward captures `ingest.normalize` has to survive (PLAN.md step 3).

An extension of `make_canary.py`: the same deterministic frames, wrapped in the containers
and damaged in the ways that spec §8's order of operations enumerates — truncated pcap,
truncated pcapng, multiple link types in one pcapng, an unreadable header, and gzipped
variants of each.

**Nothing here is committed as a binary.** `tests/test_ingest.py` imports this module and
writes the fixtures into `tmp_path`, so what a test asserts against is generated by code that
is reviewed alongside it. Committed capture bytes are unreviewable, and the repo is public.

Every writer is byte-deterministic — fixed timestamps, sequence numbers and IP IDs from
`make_canary`, gzip written with `mtime=0` — so a fixture can be regenerated and byte-
compared, and `write_plain_pcap` reproduces the committed `benign.pcap` exactly.

The truncating writers **return the byte offset of the incomplete record or block**, which is
what `NormalizedCapture.truncated_at_offset` must independently rediscover by walking. The
generator computes it while writing; `ingest.py` finds it by reading. They are two
implementations of the same arithmetic, which is the point.

Usage:
    python tests/fixtures/make_awkward.py [outdir]
"""

from __future__ import annotations

import gzip
import struct
import sys
from pathlib import Path

from make_canary import LINKTYPE_ETHERNET, build_packets, write_pcap

#: pcap file header, then a 16-byte header per record (spec §8's "record headers").
PCAP_HEADER_BYTES = 24
PCAP_RECORD_HEADER_BYTES = 16

#: pcapng block layout: type, total length, body, total length again.
PCAPNG_SHB = 0x0A0D0D0A
PCAPNG_IDB = 0x00000001
PCAPNG_EPB = 0x00000006
BYTE_ORDER_MAGIC = 0x1A2B3C4D

#: libpcap link types used by the multi-datalink fixtures. 113 (`LINUX_SLL`) is a real type
#: Wireshark can name; 147 (`USER0`) deliberately has no `editcap -T` name, which is the case
#: that has to fail loudly rather than guess.
LINKTYPE_LINUX_SLL = 113
LINKTYPE_USER0 = 147

#: Wall-clock-free timestamps, so every fixture is byte-identical run to run.
BASE_TS = 1700000000.0


# --- pcapng writing ------------------------------------------------------------------------


def _block(block_type: int, body: bytes) -> bytes:
    """One pcapng block: little-endian, body padded to a 4-byte boundary."""
    body = body + b"\x00" * (-len(body) % 4)
    total = 12 + len(body)
    return struct.pack("<II", block_type, total) + body + struct.pack("<I", total)


def section_header_block() -> bytes:
    """SHB with the little-endian byte-order magic and an unspecified section length."""
    return _block(PCAPNG_SHB, struct.pack("<IHHq", BYTE_ORDER_MAGIC, 1, 0, -1))


def interface_description_block(linktype: int, snaplen: int = 65535) -> bytes:
    return _block(PCAPNG_IDB, struct.pack("<HHI", linktype, 0, snaplen))


def enhanced_packet_block(interface_id: int, timestamp: float, frame: bytes) -> bytes:
    """EPB with microsecond timestamps, matching the IDB default time resolution."""
    micros = int(round(timestamp * 1_000_000))
    header = struct.pack(
        "<IIIII", interface_id, micros >> 32, micros & 0xFFFFFFFF, len(frame), len(frame)
    )
    return _block(PCAPNG_EPB, header + frame)


def pcapng_bytes(
    records: list[tuple[int, float, bytes]],
    linktypes: tuple[int, ...] = (LINKTYPE_ETHERNET,),
) -> bytes:
    """A complete pcapng: one SHB, one IDB per link type, then the records in order."""
    blob = section_header_block()
    for linktype in linktypes:
        blob += interface_description_block(linktype)
    for interface_id, timestamp, frame in records:
        blob += enhanced_packet_block(interface_id, timestamp, frame)
    return blob


def pcapng_block_offset(
    records: list[tuple[int, float, bytes]],
    index: int,
    linktypes: tuple[int, ...] = (LINKTYPE_ETHERNET,),
) -> int:
    """Byte offset at which record `index` (0-based) begins."""
    offset = len(section_header_block()) + sum(
        len(interface_description_block(linktype)) for linktype in linktypes
    )
    for interface_id, timestamp, frame in records[:index]:
        offset += len(enhanced_packet_block(interface_id, timestamp, frame))
    return offset


# --- pcap writing --------------------------------------------------------------------------


def pcap_bytes(packets: list[tuple[float, bytes]], path: Path) -> bytes:
    """Delegate to the canary's writer, so both fixtures share one pcap encoder.

    `make_canary.write_pcap` writes to a path rather than returning bytes; reusing it and
    reading the result back keeps a single implementation of the container format instead of
    a second one here that could drift.
    """
    write_pcap(str(path), packets)
    return path.read_bytes()


def pcap_record_offset(packets: list[tuple[float, bytes]], index: int) -> int:
    """Byte offset at which record `index` (0-based) begins in a pcap file."""
    return PCAP_HEADER_BYTES + sum(
        PCAP_RECORD_HEADER_BYTES + len(frame) for _, frame in packets[:index]
    )


#: The four pcap magics spec §8 step 1 requires sniffing, as (struct order, nanosecond).
#: `("<", False)` is what `make_canary` writes; the other three exist because a capture from a
#: big-endian host or a nanosecond-resolution capture is an ordinary file, not a corner case,
#: and a reader that only handles the common magic fails on it at the first record header.
PCAP_VARIANTS: dict[str, tuple[str, bool]] = {
    "little-endian-microsecond": ("<", False),
    "big-endian-microsecond": (">", False),
    "little-endian-nanosecond": ("<", True),
    "big-endian-nanosecond": (">", True),
}


def write_pcap_variant(path: Path, byte_order: str = "<", nanosecond: bool = False) -> Path:
    """The canary packets in any of the four pcap byte-order / precision combinations.

    With the defaults this reproduces `make_canary.write_pcap` byte for byte, which is what
    keeps this second encoder honest about being the same format.
    """
    magic = 0xA1B23C4D if nanosecond else 0xA1B2C3D4
    divisor = 1_000_000_000 if nanosecond else 1_000_000
    blob = struct.pack(byte_order + "IHHiIII", magic, 2, 4, 0, 0, 65535, LINKTYPE_ETHERNET)
    for timestamp, frame in build_packets():
        seconds = int(timestamp)
        fraction = int(round((timestamp - seconds) * divisor))
        blob += struct.pack(byte_order + "IIII", seconds, fraction, len(frame), len(frame))
        blob += frame
    path.write_bytes(blob)
    return path


# --- the fixtures --------------------------------------------------------------------------


def multi_datalink_records(ethernet: int = 10, other: int = 4) -> list[tuple[int, float, bytes]]:
    """Records split across two interfaces, in one interleaving-free run each.

    The second interface's frames are the canary's IP payloads behind a 16-byte pseudo
    link-layer header, so they are structurally plausible for a cooked-capture link type
    without needing a second frame builder.
    """
    packets = build_packets()
    records: list[tuple[int, float, bytes]] = [
        (0, timestamp, frame) for timestamp, frame in packets[:ethernet]
    ]
    for timestamp, frame in packets[ethernet : ethernet + other]:
        records.append((1, timestamp, b"\x00" * 16 + frame[14:]))
    return records


def write_plain_pcap(path: Path) -> Path:
    """The canary capture, byte-for-byte — the complete-input control case."""
    write_pcap(str(path), build_packets())
    return path


def write_plain_pcapng(path: Path) -> Path:
    """A single-link-type pcapng: the plain `editcap -F pcap` conversion path."""
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    path.write_bytes(pcapng_bytes(records))
    return path


def write_truncated_pcap(path: Path, keep: int = 10, missing: int = 8) -> int:
    """A pcap cut short inside record `keep`. Returns that record's byte offset.

    `missing` bytes are removed from the end of that record. Pass a value larger than the
    frame to cut inside the 16-byte record header itself — the case where there is not even a
    length to read, which must still report the offset of the record that started.
    """
    packets = build_packets()
    blob = pcap_bytes(packets, path)
    offset = pcap_record_offset(packets, keep)
    record_length = PCAP_RECORD_HEADER_BYTES + len(packets[keep][1])
    if not 0 < missing < record_length:
        raise ValueError(f"missing must be within 1..{record_length - 1}, got {missing}")
    path.write_bytes(blob[: offset + record_length - missing])
    return offset


def write_truncated_pcapng(path: Path, keep: int = 10, missing: int = 8) -> int:
    """A pcapng cut short inside packet block `keep`. Returns that block's byte offset."""
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    blob = pcapng_bytes(records)
    offset = pcapng_block_offset(records, keep)
    block_length = len(enhanced_packet_block(*records[keep]))
    if not 0 < missing < block_length:
        raise ValueError(f"missing must be within 1..{block_length - 1}, got {missing}")
    path.write_bytes(blob[: offset + block_length - missing])
    return offset


def write_multi_datalink_pcapng(
    path: Path,
    ethernet: int = 10,
    other: int = 4,
    other_linktype: int = LINKTYPE_LINUX_SLL,
) -> Path:
    """A pcapng carrying two link types. Ethernet dominates unless told otherwise."""
    records = multi_datalink_records(ethernet, other)
    path.write_bytes(pcapng_bytes(records, (LINKTYPE_ETHERNET, other_linktype)))
    return path


def write_bad_header(path: Path) -> Path:
    """A file whose first bytes match no capture magic — spec §8 step 4.

    Given a `.pcap` name on purpose: sniffing is by magic bytes, never by extension, and this
    fixture is what proves the extension is not consulted.
    """
    path.write_bytes(b"NOTACAPTURE\n" + bytes(range(52)))
    return path


def write_gzipped(source: Path, path: Path) -> Path:
    """Gzip `source` deterministically: no stored filename, no mtime."""
    with path.open("wb") as raw, gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
        gz.write(source.read_bytes())
    return path


def write_corrupt_gzip(path: Path) -> Path:
    """Gzip magic followed by bytes that are not a gzip member."""
    path.write_bytes(b"\x1f\x8b" + bytes(range(62)))
    return path


def write_all(outdir: Path) -> dict[str, Path]:
    """Write every fixture into `outdir`, returning name -> path.

    Kept as one function so the module's `main` and the test suite produce exactly the same
    set: a fixture that only exists when a test asks for it inline is a fixture nobody else
    can reproduce from the command line.
    """
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}

    written["plain.pcap"] = write_plain_pcap(outdir / "plain.pcap")
    written["plain.pcapng"] = write_plain_pcapng(outdir / "plain.pcapng")
    write_truncated_pcap(outdir / "truncated.pcap")
    written["truncated.pcap"] = outdir / "truncated.pcap"
    write_truncated_pcap(outdir / "truncated_record_header.pcap", missing=80)
    written["truncated_record_header.pcap"] = outdir / "truncated_record_header.pcap"
    write_truncated_pcapng(outdir / "truncated.pcapng")
    written["truncated.pcapng"] = outdir / "truncated.pcapng"
    written["multi_datalink.pcapng"] = write_multi_datalink_pcapng(outdir / "multi_datalink.pcapng")
    written["multi_datalink_sll_dominant.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_sll_dominant.pcapng", ethernet=4, other=10
    )
    written["multi_datalink_tie.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_tie.pcapng", ethernet=7, other=7
    )
    written["multi_datalink_unnameable.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_unnameable.pcapng",
        ethernet=4,
        other=10,
        other_linktype=LINKTYPE_USER0,
    )
    for variant, (byte_order, nanosecond) in PCAP_VARIANTS.items():
        name = f"{variant}.pcap"
        written[name] = write_pcap_variant(outdir / name, byte_order, nanosecond)
    written["bad_header.pcap"] = write_bad_header(outdir / "bad_header.pcap")
    written["corrupt.pcap.gz"] = write_corrupt_gzip(outdir / "corrupt.pcap.gz")

    for name in ("plain.pcap", "plain.pcapng", "truncated.pcap", "bad_header.pcap"):
        written[f"{name}.gz"] = write_gzipped(written[name], outdir / f"{name}.gz")

    return written


def main() -> int:
    outdir = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    for name, path in sorted(write_all(outdir).items()):
        print(f"wrote {name}: {path.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
