"""Generate the awkward captures `ingest.normalize` has to survive (PLAN.md step 3).

An extension of `make_canary.py`: the same deterministic frames, wrapped in the containers
and damaged in the ways that spec §8's order of operations enumerates — truncated pcap,
truncated pcapng, multiple link types in one pcapng, an unreadable header, structurally
corrupt blocks, and gzipped variants of each.

**Nothing here is committed as a binary.** `tests/test_ingest.py` imports this module and
writes the fixtures into `tmp_path`, so what a test asserts against is generated by code that
is reviewed alongside it. Committed capture bytes are unreviewable, and the repo is public.

Every writer is byte-deterministic — fixed timestamps, sequence numbers and IP IDs from
`make_canary`, gzip written with `mtime=0` — so a fixture can be regenerated and byte-
compared, and `write_plain_pcap` reproduces the committed `benign.pcap` exactly.

The truncating writers **return the byte offset of the incomplete record or block**, which is
what `NormalizedCapture.truncated_at_offset` must independently rediscover by walking. The
generator computes it while writing; `ingest.py` finds it by reading. They are two
implementations of the same arithmetic, which is the point.

Usage:
    python tests/fixtures/make_awkward.py <outdir>

`outdir` is required and deliberately has no default. Defaulting to the working directory
makes the documented command write capture blobs wherever it is run — including into the
repository, where `.gitignore` does not cover `*.gz` — and this repo is public.
"""

from __future__ import annotations

import gzip
import struct
import sys
from pathlib import Path

from make_canary import LINKTYPE_ETHERNET, build_packets, write_pcap

#: pcap file header, then a 16-byte header per record (spec §8's "record headers").
PCAP_HEADER_BYTES = 24
PCAP_RECORD_HEADER_BYTES = 16

#: pcapng block layout: type, total length, body, total length again.
PCAPNG_SHB = 0x0A0D0D0A
PCAPNG_IDB = 0x00000001
PCAPNG_EPB = 0x00000006
#: Decryption secrets block. Wireshark uses it to embed TLS key logs, so a capture carrying a
#: multi-megabyte one is ordinary — which is what makes it the right fixture for proving the
#: per-packet size bound is not applied to every block type.
PCAPNG_DSB = 0x0000000A
BYTE_ORDER_MAGIC = 0x1A2B3C4D

#: libpcap link types used by the multi-datalink fixtures. 113 (`LINUX_SLL`) is a real type
#: Wireshark can name; 147 (`USER0`) deliberately has no `editcap -T` name, which is the case
#: that has to fail loudly rather than guess.
LINKTYPE_LINUX_SLL = 113
LINKTYPE_USER0 = 147

#: Wall-clock-free timestamps, so every fixture is byte-identical run to run.
BASE_TS = 1700000000.0


# --- pcapng writing ------------------------------------------------------------------------


def _block(block_type: int, body: bytes, order: str = "<") -> bytes:
    """One pcapng block, body padded to a 4-byte boundary, in the given byte order."""
    body = body + b"\x00" * (-len(body) % 4)
    total = 12 + len(body)
    return struct.pack(order + "II", block_type, total) + body + struct.pack(order + "I", total)


def section_header_block(order: str = "<") -> bytes:
    """SHB with the byte-order magic packed in `order` and an unspecified section length.

    The magic is what tells a reader the endianness of everything after it, so packing it in
    `order` is the whole mechanism a big-endian pcapng fixture needs.
    """
    return _block(PCAPNG_SHB, struct.pack(order + "IHHq", BYTE_ORDER_MAGIC, 1, 0, -1), order)


def interface_description_block(linktype: int, snaplen: int = 65535, order: str = "<") -> bytes:
    return _block(PCAPNG_IDB, struct.pack(order + "HHI", linktype, 0, snaplen), order)


def enhanced_packet_block(
    interface_id: int, timestamp: float, frame: bytes, order: str = "<"
) -> bytes:
    """EPB with microsecond timestamps, matching the IDB default time resolution."""
    micros = int(round(timestamp * 1_000_000))
    header = struct.pack(
        order + "IIIII", interface_id, micros >> 32, micros & 0xFFFFFFFF, len(frame), len(frame)
    )
    return _block(PCAPNG_EPB, header + frame, order)


def pcapng_bytes(
    records: list[tuple[int, float, bytes]],
    linktypes: tuple[int, ...] = (LINKTYPE_ETHERNET,),
    order: str = "<",
) -> bytes:
    """A complete pcapng: one SHB, one IDB per link type, then the records in order.

    `linktypes` is one entry per *interface*, not per distinct link type — two interfaces may
    share one, which is what a real multi-interface capture looks like and what a selection
    filter has to handle.
    """
    blob = section_header_block(order)
    for linktype in linktypes:
        blob += interface_description_block(linktype, order=order)
    for interface_id, timestamp, frame in records:
        blob += enhanced_packet_block(interface_id, timestamp, frame, order)
    return blob


def pcapng_block_offset(
    records: list[tuple[int, float, bytes]],
    index: int,
    linktypes: tuple[int, ...] = (LINKTYPE_ETHERNET,),
    order: str = "<",
) -> int:
    """Byte offset at which record `index` (0-based) begins."""
    offset = len(section_header_block(order)) + sum(
        len(interface_description_block(linktype, order=order)) for linktype in linktypes
    )
    for interface_id, timestamp, frame in records[:index]:
        offset += len(enhanced_packet_block(interface_id, timestamp, frame, order))
    return offset


# --- pcap writing --------------------------------------------------------------------------


def pcap_bytes(packets: list[tuple[float, bytes]], path: Path) -> bytes:
    """Delegate to the canary's writer, so both fixtures share one pcap encoder.

    `make_canary.write_pcap` writes to a path rather than returning bytes; reusing it and
    reading the result back keeps a single implementation of the container format instead of
    a second one here that could drift.
    """
    write_pcap(str(path), packets)
    return path.read_bytes()


def pcap_record_offset(packets: list[tuple[float, bytes]], index: int) -> int:
    """Byte offset at which record `index` (0-based) begins in a pcap file."""
    return PCAP_HEADER_BYTES + sum(
        PCAP_RECORD_HEADER_BYTES + len(frame) for _, frame in packets[:index]
    )


#: The four pcap magics spec §8 step 1 requires sniffing, as (struct order, nanosecond).
#: `("<", False)` is what `make_canary` writes; the other three exist because a capture from a
#: big-endian host or a nanosecond-resolution capture is an ordinary file, not a corner case,
#: and a reader that only handles the common magic fails on it at the first record header.
PCAP_VARIANTS: dict[str, tuple[str, bool]] = {
    "little-endian-microsecond": ("<", False),
    "big-endian-microsecond": (">", False),
    "little-endian-nanosecond": ("<", True),
    "big-endian-nanosecond": (">", True),
}


def write_pcap_variant(path: Path, byte_order: str = "<", nanosecond: bool = False) -> Path:
    """The canary packets in any of the four pcap byte-order / precision combinations.

    With the defaults this reproduces `make_canary.write_pcap` byte for byte, which is what
    keeps this second encoder honest about being the same format.
    """
    magic = 0xA1B23C4D if nanosecond else 0xA1B2C3D4
    divisor = 1_000_000_000 if nanosecond else 1_000_000
    blob = struct.pack(byte_order + "IHHiIII", magic, 2, 4, 0, 0, 65535, LINKTYPE_ETHERNET)
    for timestamp, frame in build_packets():
        seconds = int(timestamp)
        fraction = int(round((timestamp - seconds) * divisor))
        blob += struct.pack(byte_order + "IIII", seconds, fraction, len(frame), len(frame))
        blob += frame
    path.write_bytes(blob)
    return path


# --- the fixtures --------------------------------------------------------------------------


def multi_datalink_records(ethernet: int = 10, other: int = 4) -> list[tuple[int, float, bytes]]:
    """Records split across two interfaces, in one interleaving-free run each.

    The second interface's frames are the canary's IP payloads behind a 16-byte pseudo
    link-layer header, so they are structurally plausible for a cooked-capture link type
    without needing a second frame builder.
    """
    packets = build_packets()
    records: list[tuple[int, float, bytes]] = [
        (0, timestamp, frame) for timestamp, frame in packets[:ethernet]
    ]
    for timestamp, frame in packets[ethernet : ethernet + other]:
        records.append((1, timestamp, b"\x00" * 16 + frame[14:]))
    return records


def write_plain_pcap(path: Path) -> Path:
    """The canary capture, byte-for-byte — the complete-input control case."""
    write_pcap(str(path), build_packets())
    return path


def write_plain_pcapng(path: Path, order: str = "<") -> Path:
    """A single-link-type pcapng: the plain `editcap -F pcap` conversion path."""
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    path.write_bytes(pcapng_bytes(records, order=order))
    return path


def write_big_endian_pcapng(path: Path) -> Path:
    """The same capture written big-endian, which a reader must detect from the SHB.

    pcapng puts no endianness in its magic — the block type is a palindrome — so the byte
    order comes from the byte-order magic *inside* the first block. A reader that assumes
    little-endian gets absurd block lengths from the second block onwards.
    """
    return write_plain_pcapng(path, order=">")


def write_truncated_pcap(path: Path, keep: int = 10, missing: int = 8) -> int:
    """A pcap cut short inside record `keep`. Returns that record's byte offset.

    `missing` bytes are removed from the end of that record. Pass a value larger than the
    frame to cut inside the 16-byte record header itself — the case where there is not even a
    length to read, which must still report the offset of the record that started.
    """
    packets = build_packets()
    blob = pcap_bytes(packets, path)
    offset = pcap_record_offset(packets, keep)
    record_length = PCAP_RECORD_HEADER_BYTES + len(packets[keep][1])
    if not 0 < missing < record_length:
        raise ValueError(f"missing must be within 1..{record_length - 1}, got {missing}")
    path.write_bytes(blob[: offset + record_length - missing])
    return offset


def write_truncated_pcapng(path: Path, keep: int = 10, missing: int = 8) -> int:
    """A pcapng cut short inside packet block `keep`. Returns that block's byte offset."""
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    blob = pcapng_bytes(records)
    offset = pcapng_block_offset(records, keep)
    block_length = len(enhanced_packet_block(*records[keep]))
    if not 0 < missing < block_length:
        raise ValueError(f"missing must be within 1..{block_length - 1}, got {missing}")
    path.write_bytes(blob[: offset + block_length - missing])
    return offset


def write_multi_datalink_pcapng(
    path: Path,
    ethernet: int = 10,
    other: int = 4,
    other_linktype: int = LINKTYPE_LINUX_SLL,
) -> Path:
    """A pcapng carrying two link types. Ethernet dominates unless told otherwise."""
    records = multi_datalink_records(ethernet, other)
    path.write_bytes(pcapng_bytes(records, (LINKTYPE_ETHERNET, other_linktype)))
    return path


def write_interleaved_multi_datalink_pcapng(path: Path) -> Path:
    """Three interfaces, two of them Ethernet, interleaved packet by packet.

    This is what `dumpcap -i eth0 -i lo` actually produces, and it breaks two tempting
    shortcuts at once: link types do not arrive in runs (so selecting by packet-number range
    grows with the capture), and one link type can span several interfaces (so a filter on a
    single `frame.interface_id` silently drops packets it should keep).
    """
    frames = build_packets()
    interfaces = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 2, 0][: len(frames)]
    records: list[tuple[int, float, bytes]] = []
    for interface, (timestamp, frame) in zip(interfaces, frames, strict=True):
        payload = frame if interface != 1 else b"\x00" * 16 + frame[14:]
        records.append((interface, timestamp, payload))
    path.write_bytes(
        pcapng_bytes(records, (LINKTYPE_ETHERNET, LINKTYPE_LINUX_SLL, LINKTYPE_ETHERNET))
    )
    return path


def interleaved_ethernet_frames() -> list[bytes]:
    """The frames `write_interleaved_multi_datalink_pcapng` puts on its Ethernet interfaces.

    Returned so a test can assert the *right* packets survived, not merely the right number.
    """
    frames = build_packets()
    interfaces = [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 2, 0][: len(frames)]
    return [
        frame for interface, (_, frame) in zip(interfaces, frames, strict=True) if interface != 1
    ]


def write_bad_header(path: Path) -> Path:
    """A file whose first bytes match no capture magic — spec §8 step 4.

    Given a `.pcap` name on purpose: sniffing is by magic bytes, never by extension, and this
    fixture is what proves the extension is not consulted.
    """
    path.write_bytes(b"NOTACAPTURE\n" + bytes(range(52)))
    return path


def write_short_pcap_header(path: Path, kept: int = 12) -> Path:
    """A file with real pcap magic and a file header cut off mid-way.

    Sniffing succeeds — the magic is genuine — so this is the case that has to be caught by
    the walk, before anything unpacks 24 bytes of fields out of 12.
    """
    packets = build_packets()
    blob = pcap_bytes(packets, path)
    path.write_bytes(blob[:kept])
    return path


def write_pcapng_bad_block_length(path: Path, block: int = 3, length: int = 13) -> tuple[Path, int]:
    """A pcapng whose packet block `block` declares `length` as its size. Returns its offset.

    The default 13 is neither a multiple of 4 nor large enough to hold a block's own framing,
    so no plausible reading of the file makes it valid. Pass a huge `length` instead for the
    other kind of unreadable header — a packet claiming more bytes than a frame can hold.
    """
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    blob = bytearray(pcapng_bytes(records))
    offset = pcapng_block_offset(records, block)
    blob[offset + 4 : offset + 8] = struct.pack("<I", length)
    path.write_bytes(bytes(blob))
    return path, offset


def write_pcapng_trailer_mismatch(path: Path, block: int = 3) -> tuple[Path, int]:
    """A pcapng where a block's trailing length disagrees with its leading one.

    pcapng writes the length at both ends precisely so a reader can catch this, and catching
    it is the difference between a diagnosis and reading the next block from the wrong offset.
    """
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    blob = bytearray(pcapng_bytes(records))
    offset = pcapng_block_offset(records, block)
    total = struct.unpack("<I", blob[offset + 4 : offset + 8])[0]
    blob[offset + total - 4 : offset + total] = struct.pack("<I", total + 4)
    path.write_bytes(bytes(blob))
    return path, offset


def write_pcapng_undefined_interface(path: Path, interface: int = 5) -> Path:
    """A pcapng whose packets claim an interface no IDB describes.

    Their link type is then unknowable, which matters: link type decides whether a conversion
    is even possible, so this cannot be defaulted to "probably Ethernet".
    """
    records = [(interface, timestamp, frame) for timestamp, frame in build_packets()]
    path.write_bytes(pcapng_bytes(records, (LINKTYPE_ETHERNET,)))
    return path


def write_pcapng_short_block_body(path: Path) -> Path:
    """A pcapng whose IDB is a valid 12-byte block with no body at all.

    Structurally legal as a block — the length is a multiple of 4 and at least 12 — but too
    short to hold the link type it is supposed to declare. Unpacking it anyway raises
    `struct.error`, which is not a `FlabelError`, so the operator would get a traceback.
    """
    empty_idb = struct.pack("<II", PCAPNG_IDB, 12) + struct.pack("<I", 12)
    path.write_bytes(section_header_block() + empty_idb)
    return path


def write_pcapng_with_large_secrets_block(path: Path, body_bytes: int = 17 * 1024 * 1024) -> Path:
    """A valid pcapng carrying a decryption secrets block larger than a packet may be.

    Wireshark embeds TLS key logs this way, so multi-megabyte non-packet blocks are ordinary.
    A size bound applied to every block type — rather than to packets only — would reject this
    perfectly good capture as corrupt, and a reader that loads block bodies rather than
    skipping them would pull all of it into memory.
    """
    records = [(0, timestamp, frame) for timestamp, frame in build_packets()]
    secrets = _block(PCAPNG_DSB, b"\x00" * body_bytes)
    blob = section_header_block() + interface_description_block(LINKTYPE_ETHERNET) + secrets
    for record in records:
        blob += enhanced_packet_block(*record)
    path.write_bytes(blob)
    return path


def write_gzipped(source: Path, path: Path) -> Path:
    """Gzip `source` deterministically: no stored filename, no mtime."""
    with path.open("wb") as raw, gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
        gz.write(source.read_bytes())
    return path


def write_corrupt_gzip(path: Path) -> Path:
    """Gzip magic followed by bytes that are not a gzip member."""
    path.write_bytes(b"\x1f\x8b" + bytes(range(62)))
    return path


def write_all(outdir: Path) -> dict[str, Path]:
    """Write every fixture into `outdir`, returning name -> path.

    Kept as one function so the module's `main` and the test suite produce exactly the same
    set: a fixture that only exists when a test asks for it inline is a fixture nobody else
    can reproduce from the command line.
    """
    outdir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}

    written["plain.pcap"] = write_plain_pcap(outdir / "plain.pcap")
    written["plain.pcapng"] = write_plain_pcapng(outdir / "plain.pcapng")
    write_truncated_pcap(outdir / "truncated.pcap")
    written["truncated.pcap"] = outdir / "truncated.pcap"
    write_truncated_pcap(outdir / "truncated_record_header.pcap", missing=80)
    written["truncated_record_header.pcap"] = outdir / "truncated_record_header.pcap"
    write_truncated_pcapng(outdir / "truncated.pcapng")
    written["truncated.pcapng"] = outdir / "truncated.pcapng"
    written["multi_datalink.pcapng"] = write_multi_datalink_pcapng(outdir / "multi_datalink.pcapng")
    written["multi_datalink_sll_dominant.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_sll_dominant.pcapng", ethernet=4, other=10
    )
    written["multi_datalink_tie.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_tie.pcapng", ethernet=7, other=7
    )
    written["multi_datalink_unnameable.pcapng"] = write_multi_datalink_pcapng(
        outdir / "multi_datalink_unnameable.pcapng",
        ethernet=4,
        other=10,
        other_linktype=LINKTYPE_USER0,
    )
    written["interleaved_multi_datalink.pcapng"] = write_interleaved_multi_datalink_pcapng(
        outdir / "interleaved_multi_datalink.pcapng"
    )
    written["big_endian.pcapng"] = write_big_endian_pcapng(outdir / "big_endian.pcapng")
    for variant, (byte_order, nanosecond) in PCAP_VARIANTS.items():
        name = f"{variant}.pcap"
        written[name] = write_pcap_variant(outdir / name, byte_order, nanosecond)
    written["bad_header.pcap"] = write_bad_header(outdir / "bad_header.pcap")
    written["short_header.pcap"] = write_short_pcap_header(outdir / "short_header.pcap")
    written["bad_block_length.pcapng"] = write_pcapng_bad_block_length(
        outdir / "bad_block_length.pcapng"
    )[0]
    written["trailer_mismatch.pcapng"] = write_pcapng_trailer_mismatch(
        outdir / "trailer_mismatch.pcapng"
    )[0]
    written["undefined_interface.pcapng"] = write_pcapng_undefined_interface(
        outdir / "undefined_interface.pcapng"
    )
    written["short_block_body.pcapng"] = write_pcapng_short_block_body(
        outdir / "short_block_body.pcapng"
    )
    written["corrupt.pcap.gz"] = write_corrupt_gzip(outdir / "corrupt.pcap.gz")

    for name in ("plain.pcap", "plain.pcapng", "truncated.pcap", "truncated.pcapng"):
        written[f"{name}.gz"] = write_gzipped(written[name], outdir / f"{name}.gz")

    return written


def main() -> int:
    """Write every fixture into an explicitly named directory.

    `write_pcapng_with_large_secrets_block` is left out: it is 17 MB, exists only to prove a
    size bound is not misapplied, and generating it by default would make the documented
    command surprisingly expensive.
    """
    if len(sys.argv) != 2:
        print(f"usage: {Path(sys.argv[0]).name} <outdir>", file=sys.stderr)
        print("outdir is required — see this module's docstring for why.", file=sys.stderr)
        return 2
    for name, path in sorted(write_all(Path(sys.argv[1])).items()):
        print(f"wrote {name}: {path.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
